In [1]:
import pandas as pd

In [2]:
# 해당 연, 월
year = 2022
month = 9

In [3]:
# 서울시 공문번호 입력
doc_num = "서울시 친환경차량과-2059(2022.10.11.)"

In [4]:
# 엑셀 파일 이름
excel_file = f"전기자동차 등록원부 표기 대상({month}월분).xlsx"

In [5]:
# 첫번째 시트 : 전기차
car1 = pd.read_excel(excel_file, dtype="string", header=4, sheet_name=0)
car1

,차종구분,신청\n번호,지급일자,차종,신청\n대수,신청자명,주소\n(등록주소지),신청\n총금액(만원),국비(만원),도비(만원),시비(만원),추가\n보조금(만원),차량번호,차대번호,차량출고일,차량등록일
0,전기승용,14325,2022-09-28,니로 플러스 / 일반승용,1,한옥수,서울특별시 관악구 신림로36길 24-5 .,1200,900,0,200,100,서울31사5618,KNAA381GFPT005070,2022-09-14,2022-09-15
1,전기승용,14108,2022-09-28,EV6 롱레인지 4WD 19인치 / 일반승용,1,변호빈,서울특별시 동작구 여의대방로44길 47 205동 908호,1200,900,0,200,100,서울31자8444,KNAC281CPNA086992,2022-09-07,2022-09-14
2,전기승용,14078,2022-09-28,볼트 EUV / 일반승용,1,박진우,"서울특별시 영등포구 선유로9나길 5 102동1005호(문래동5가,문래동모아미래도아파트)",861,670,0,191,0,40구4863,1G1F66S09N4130229,2022-09-07,2022-09-13
3,전기승용,14077,2022-09-28,EV6 롱레인지 2WD 19인치 / 일반승용,1,권병준,서울특별시 금천구 시흥대로 291 306동 4305호,1200,900,0,200,100,서울31바4374,KNAC281AFNA087019,2022-09-14,2022-09-15
4,전기승용,14072,2022-09-28,니로 플러스 / 일반승용,1,표결종,경기도 김포시 감정로 87 110동 1304호,1200,900,0,200,100,서울31자2088,KNAA381GFPT005139,2022-09-08,2022-09-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,전기화물,3173,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),2,주식회사 도곡센타,"서울특별시 서초구 마방로6길 46 1층 101호 (양재동,혜전빌딩)",4000,2800,0,1200,0,90루8116 90루8485,KMFZCZ7NFNU035862 KMFZCZ7NFNU036245,2022-07-29 2022-07-29,2022-08-03 2022-08-03
1667,전기화물,3094,2022-09-22,포터Ⅱ 일렉트릭 / 화물(소형),1,이정임,서울특별시 강동구 고덕로61길 37 101동603호,2000,1400,0,600,0,89도3037,KMFZCZ7NFNU037855,2022-08-16,2022-08-22
1668,전기화물,3045,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),1,조상태,서울특별시 강남구 자곡로7길 22-16 106동 1402호,2000,1400,0,600,0,82라8762,KMFZCZ7NFNU038009,2022-08-16,2022-08-18
1669,전기화물,2984,2022-09-15,봉고Ⅲ 전기차 / 화물(소형),1,김원주,서울특별시 영등포구 여의대방로 45 2동 1003호,2000,1400,0,600,0,서울80배3165,KNFSTZ7NFNK026712,2022-08-02,2022-08-08
1670,전기화물,1509,2022-09-15,봉고Ⅲ 전기차 / 화물(소형),1,박동준,서울특별시 금천구 독산로 107 401호,2000,1400,0,600,0,84조3286,KNCSJZ7NFNK026449,2022-07-22,2022-07-28

In [6]:
# 두번째 시트 : 수소차(엑셀파일에서 두번째 시트가 없거나, 건설기계인 경우는 이번 셀 생략)

# car2 = pd.read_excel(excel_file, dtype="string", header=4, sheet_name=1)
# car2

In [7]:
# 두번째 시트가 없었다면 이어붙일 필요가 없다

# cars = pd.concat([car1, car2], ignore_index=True)
# cars
cars = car1

In [8]:
# 열 이름 가져오기
cars.keys()

Index(['차종구분', '신청\n번호', '지급일자', '차종', '신청\n대수', '신청자명', '주소\n(등록주소지)',
       '신청\n총금액(만원)', '국비(만원)', '도비(만원)', '시비(만원)', '추가\n보조금(만원)', '차량번호',
       '차대번호', '차량출고일', '차량등록일'],
      dtype='object')

In [9]:
# 열 이름을 알기쉽게 변경
cars.columns = ['차종구분', '신청번호', '지급일자', '차종', '신청대수', '신청자명', '주소',
       '총액', '국비', '도비', '시비', '추가', '차량번호',
       '차대번호', '차량출고일', '차량등록일']

# 불필요한 열은 삭제
cars = cars.drop(['차종구분', '신청번호', '차량출고일'], axis=1)
cars

,지급일자,차종,신청대수,신청자명,주소,총액,국비,도비,시비,추가,차량번호,차대번호,차량등록일
0,2022-09-28,니로 플러스 / 일반승용,1,한옥수,서울특별시 관악구 신림로36길 24-5 .,1200,900,0,200,100,서울31사5618,KNAA381GFPT005070,2022-09-15
1,2022-09-28,EV6 롱레인지 4WD 19인치 / 일반승용,1,변호빈,서울특별시 동작구 여의대방로44길 47 205동 908호,1200,900,0,200,100,서울31자8444,KNAC281CPNA086992,2022-09-14
2,2022-09-28,볼트 EUV / 일반승용,1,박진우,"서울특별시 영등포구 선유로9나길 5 102동1005호(문래동5가,문래동모아미래도아파트)",861,670,0,191,0,40구4863,1G1F66S09N4130229,2022-09-13
3,2022-09-28,EV6 롱레인지 2WD 19인치 / 일반승용,1,권병준,서울특별시 금천구 시흥대로 291 306동 4305호,1200,900,0,200,100,서울31바4374,KNAC281AFNA087019,2022-09-15
4,2022-09-28,니로 플러스 / 일반승용,1,표결종,경기도 김포시 감정로 87 110동 1304호,1200,900,0,200,100,서울31자2088,KNAA381GFPT005139,2022-09-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),2,주식회사 도곡센타,"서울특별시 서초구 마방로6길 46 1층 101호 (양재동,혜전빌딩)",4000,2800,0,1200,0,90루8116 90루8485,KMFZCZ7NFNU035862 KMFZCZ7NFNU036245,2022-08-03 2022-08-03
1667,2022-09-22,포터Ⅱ 일렉트릭 / 화물(소형),1,이정임,서울특별시 강동구 고덕로61길 37 101동603호,2000,1400,0,600,0,89도3037,KMFZCZ7NFNU037855,2022-08-22
1668,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),1,조상태,서울특별시 강남구 자곡로7길 22-16 106동 1402호,2000,1400,0,600,0,82라8762,KMFZCZ7NFNU038009,2022-08-18
1669,2022-09-15,봉고Ⅲ 전기차 / 화물(소형),1,김원주,서울특별시 영등포구 여의대방로 45 2동 1003호,2000,1400,0,600,0,서울80배3165,KNFSTZ7NFNK026712,2022-08-08
1670,2022-09-15,봉고Ⅲ 전기차 / 화물(소형),1,박동준,서울특별시 금천구 독산로 107 401호,2000,1400,0,600,0,84조3286,KNCSJZ7NFNK026449,2022-07-28

In [10]:
# '주소'가 '노원구'인 것들만 추출 ==> 타구 주소인데 도로명에 '노원구세군1길' 같은 것이 없는지 확인
# nowon_cars = cars[cars['주소'].str.contains('노원구')]

nowon_cars = cars[cars['주소'].str.contains('서울특별시 노원구|서울시 노원구')]
nowon_cars

,지급일자,차종,신청대수,신청자명,주소,총액,국비,도비,시비,추가,차량번호,차대번호,차량등록일
14,2022-09-28,니로 플러스 / 일반승용,1,박상군,서울특별시 노원구 동일로215길 48 325동1206호,1200,900,0,200,100,서울31사8655,KNAA381GFPT004800,2022-09-13
15,2022-09-21,EV6 롱레인지 2WD 19인치 / 일반승용,1,김양진,서울특별시 노원구 동일로207길 186 101동 1213호,900,700,0,200,0,46오6206,KNAC281AFNA085694,2022-09-07
41,2022-09-28,Model 3 RWD / 일반승용,1,김성일,서울특별시 노원구 화랑로 415-9 201호,405,315,0,90,0,06보2468,5YJ3E1EA0NF302581,2022-09-14
55,2022-09-28,GV60 스탠다드 2WD 19인치 / 일반승용,1,김휘동,서울특별시 노원구 동일로186길 49 302호,450,350,0,100,0,07구1281,KMTKB81AFNU008184,2022-08-30
71,2022-09-28,MINI Cooper SE / 일반승용,1,김수희,서울특별시 노원구 광운로22길 39 7층 701호,735,572,0,163,0,06어2145,WMW11DJ08P2S91110,2022-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),1,박상정,서울특별시 노원구 한글비석로54길 92 1305동 1201호,2000,1400,0,600,0,92부3451,KMFZSZ7NFNU035501,2022-08-04
1640,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),1,권용재,서울특별시 노원구 섬밭로 139 112동 1305호,2140,1540,0,600,0,84마7318,KMFZCZ7NFNU036574,2022-08-08
1642,2022-09-15,일진무시동전기냉동탑차(포터) / 화물(소형),1,김경수,서울특별시 노원구 중계로 230 511동 204호,2812,2024,0,788,0,서울81배3394,KMFZCZ7NFNU033046,2022-08-09
1651,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),1,이현종,서울특별시 노원구 동일로237마길 30 102호,2000,1400,0,600,0,서울80배2026,KMFZSZ7NFNU036227,2022-08-04
1657,2022-09-22,포터Ⅱ 일렉트릭 / 화물(소형),1,박대성,서울특별시 노원구 중계로6길 59 .,2000,1400,0,600,0,89도2985,KMFZCZ7NFNU038140,2022-08-24

In [11]:
# 혹시 금액 열(총액, 국비, 시비, 추가)에 소수점이 있는지 확인 ==> 모두 False여야 정상, True가 있으면 소수점 있음
realnumberTest = nowon_cars[['신청대수', '총액', '국비', '도비', '시비', '추가']].apply(lambda x: x.astype(str).str.find('.') != -1)
realnumberTest.value_counts()

신청대수   총액     국비     도비     시비     추가
False  False  False  False  False  False    66
       True   False  False  True   False     1
dtype: int64

In [23]:
nowon_cars.loc[

In [23]:
# 만약 소수점이 있다면 확인해본다.
# with pd.option_context('display.max_rows', None, 'display.max_columns', None):
#     print(nowon_cars.where(realnumberTest))
#      print(nowon_cars[['신청대수', '총액', '국비', '도비', '시비', '추가']].apply(lambda x: x.astype(str).str.contains('.')))
nowon_cars[ nowon_cars['신청대수'].str.contains('.')

      지급일자    차종  신청대수  신청자명    주소     총액    국비    도비    시비    추가  차량번호  차대번호  \
14    <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
15    <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
41    <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
55    <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
71    <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
120   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
126   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
128   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
166   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
222   <NA>  <NA>  <NA>  <NA>  <NA>  772.5  <NA>  <NA>  96.5  <NA>  <NA>  <NA>
254   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
261   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
292   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
293   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
296   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
319   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
343   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
431   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
433   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
437   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
444   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
463   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
466   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
484   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
493   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
518   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
564   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
595   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
636   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
646   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
648   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
719   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
726   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
745   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
800   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
803   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
807   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
814   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
815   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
824   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
830   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
833   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
842   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
843   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
850   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
854   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
861   <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1013  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1023  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1047  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1142  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1149  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1162  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1287  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1316  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1375  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1448  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1449  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1545  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1563  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1587  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1623  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1638  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1640  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1642  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1651  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
1657  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>

     차량등록일
14    <NA>
15    <NA>
41    <NA>
55    <NA>
71    <NA>
120   <NA>
126   <NA>
128   <NA>
166   <NA>
222   <NA>
254   <NA>
261   <NA>
292   <NA>
293   <NA>
296   <NA>
319   <NA>
343   <NA>
431   <NA>
433   <NA>
437   <NA>
444   <NA>
463   <NA>
466   <NA>
484   <NA>
493   <NA>
518   <NA>
564   <NA>
595   <NA>
636   <NA>
646   <NA>
648   <NA>
719   <NA>
726   <NA>
745   <NA>
800   <NA>
803   <NA>
807   <NA>
814   <NA>
815   <NA>
824   <NA>
830   <NA>
833   <NA>
842   <NA>
843   <NA>
850   <NA>
854   <NA>
861   <NA>
1013  <NA>
1023  <NA>
1047  <NA>
1142  <NA>
1149  <NA>
1162  <NA>
1287  <NA>
1316  <NA>
1375  <NA>
1448  <NA>
1449  <NA>
1545  <NA>
1563  <NA>
1587  <NA>
1623  <NA>
1638  <NA>
1640  <NA>
1642  <NA>
1651  <NA>
1657  <NA>

In [15]:
# 4개 열(총액, 국비, 시비, 추가) 문자열 ==> 정수형으로 변환 + 천단위 콤마 제거
pd.set_option('mode.chained_assignment', None)
nowon_cars[['신청대수', '총액', '국비', '도비', '시비', '추가']] = nowon_cars[['신청대수', '총액', '국비', '도비', '시비', '추가']].apply(lambda x: pd.to_numeric(x.astype(str).str.replace(',',''), errors='coerce'))
# nowon_cars.dtypes
nowon_cars

,지급일자,차종,신청대수,신청자명,주소,총액,국비,도비,시비,추가,차량번호,차대번호,차량등록일
14,2022-09-28,니로 플러스 / 일반승용,1,박상군,서울특별시 노원구 동일로215길 48 325동1206호,1200.0,900,0,200.0,100,서울31사8655,KNAA381GFPT004800,2022-09-13
15,2022-09-21,EV6 롱레인지 2WD 19인치 / 일반승용,1,김양진,서울특별시 노원구 동일로207길 186 101동 1213호,900.0,700,0,200.0,0,46오6206,KNAC281AFNA085694,2022-09-07
41,2022-09-28,Model 3 RWD / 일반승용,1,김성일,서울특별시 노원구 화랑로 415-9 201호,405.0,315,0,90.0,0,06보2468,5YJ3E1EA0NF302581,2022-09-14
55,2022-09-28,GV60 스탠다드 2WD 19인치 / 일반승용,1,김휘동,서울특별시 노원구 동일로186길 49 302호,450.0,350,0,100.0,0,07구1281,KMTKB81AFNU008184,2022-08-30
71,2022-09-28,MINI Cooper SE / 일반승용,1,김수희,서울특별시 노원구 광운로22길 39 7층 701호,735.0,572,0,163.0,0,06어2145,WMW11DJ08P2S91110,2022-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),1,박상정,서울특별시 노원구 한글비석로54길 92 1305동 1201호,2000.0,1400,0,600.0,0,92부3451,KMFZSZ7NFNU035501,2022-08-04
1640,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),1,권용재,서울특별시 노원구 섬밭로 139 112동 1305호,2140.0,1540,0,600.0,0,84마7318,KMFZCZ7NFNU036574,2022-08-08
1642,2022-09-15,일진무시동전기냉동탑차(포터) / 화물(소형),1,김경수,서울특별시 노원구 중계로 230 511동 204호,2812.0,2024,0,788.0,0,서울81배3394,KMFZCZ7NFNU033046,2022-08-09
1651,2022-09-15,포터Ⅱ 일렉트릭 / 화물(소형),1,이현종,서울특별시 노원구 동일로237마길 30 102호,2000.0,1400,0,600.0,0,서울80배2026,KMFZSZ7NFNU036227,2022-08-04
1657,2022-09-22,포터Ⅱ 일렉트릭 / 화물(소형),1,박대성,서울특별시 노원구 중계로6길 59 .,2000.0,1400,0,600.0,0,89도2985,KMFZCZ7NFNU038140,2022-08-24

In [17]:
nowon_cars.iloc[:15]

,지급일자,차종,신청대수,신청자명,주소,총액,국비,도비,시비,추가,차량번호,차대번호,차량등록일
14,2022-09-28,니로 플러스 / 일반승용,1,박상군,서울특별시 노원구 동일로215길 48 325동1206호,1200.0,900,0,200.0,100,서울31사8655,KNAA381GFPT004800,2022-09-13
15,2022-09-21,EV6 롱레인지 2WD 19인치 / 일반승용,1,김양진,서울특별시 노원구 동일로207길 186 101동 1213호,900.0,700,0,200.0,0,46오6206,KNAC281AFNA085694,2022-09-07
41,2022-09-28,Model 3 RWD / 일반승용,1,김성일,서울특별시 노원구 화랑로 415-9 201호,405.0,315,0,90.0,0,06보2468,5YJ3E1EA0NF302581,2022-09-14
55,2022-09-28,GV60 스탠다드 2WD 19인치 / 일반승용,1,김휘동,서울특별시 노원구 동일로186길 49 302호,450.0,350,0,100.0,0,07구1281,KMTKB81AFNU008184,2022-08-30
71,2022-09-28,MINI Cooper SE / 일반승용,1,김수희,서울특별시 노원구 광운로22길 39 7층 701호,735.0,572,0,163.0,0,06어2145,WMW11DJ08P2S91110,2022-08-31
120,2022-09-13,Electrified GV70 AWD 19인치 / 일반승용,1,이정복,서울특별시 노원구 마들로 31 112동 1501호,448.0,349,0,99.0,0,21거7579,KMTMA811PNU002811,2022-08-31
126,2022-09-28,니로 플러스 / 일반승용,1,최성일,서울특별시 노원구 월계로45길 21 117동102호,1200.0,900,0,200.0,100,서울31바6723,KNAA381GFPT004696,2022-09-06
128,2022-09-28,EV6 롱레인지 2WD 19인치 / 일반승용,1,조성암,서울특별시 노원구 동일로 1776 2층,1200.0,900,0,200.0,100,서울31사5775,KNAC281AFNA085537,2022-09-02
166,2022-09-28,EV6 롱레인지 2WD 19인치 / 일반승용,1,정진희,서울특별시 노원구 섬밭로 139 109동602호,900.0,700,0,200.0,0,21거7157,KNAC381AFNA083077,2022-08-31
222,2022-09-28,아이오닉5 AWD 롱레인지 20인치 23MY / 일반승용,1,주식회사 무한씨앤씨코리아,서울특별시 노원구 상계로23다길 46 101호,772.5,676,0,96.5,0,21거7011,KMHKR81FPPU129982,2022-09-08
254,2022-09-13,The all-new Kia Niro EV / 일반승용,1,박찬일,서울특별시 노원구 동일로230가길 15 103동1504호,900.0,700,0,200.0,0,21거7177,KNACR811FPA013189,2022-08-25
261,2022-09-28,Model Y Long Range 50 / 일반승용,1,주식회사 개념과의식있는이들,서울특별시 노원구 상계로5길 19 5층,360.0,315,0,45.0,0,52무8446,7SAYGDEE6NF500184,2022-09-15
292,2022-09-28,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 23MY / 일반승용,1,김병흔,서울특별시 노원구 노원로 564 1006동 901호,1200.0,900,0,200.0,100,서울31바4481,KMHKL81EFPU124574,2022-09-06
293,2022-09-28,Model Y Long Range 50 / 일반승용,1,신정은,서울특별시 노원구 섬밭로 196 602동 1305호,405.0,315,0,90.0,0,31버8244,7SAYGDEE2NF500179,2022-09-14
296,2022-09-28,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 23MY / 일반승용,1,송수학,서울특별시 노원구 동일로 1776 2층,1200.0,900,0,200.0,100,서울32사7407,KMHKL81EFPU124552,2022-09-05

In [16]:
# 신청대수가 2대 이상인 경우 걸러내기(엑셀 행 1개에 여러대인 경우 1/N)
# ==> 아무것도 나오지 않아야 정상
nowon_cars[nowon_cars['신청대수'] != 1]

Empty DataFrame
Columns: [지급일자, 차종, 신청대수, 신청자명, 주소, 총액, 국비, 도비, 시비, 추가, 차량번호, 차대번호, 차량등록일]
Index: []

### 한줄에 여러대(멀티케이스) 존재하는 경우 ==> 처리 시작

In [12]:
# 한줄 여러대(멀티케이스)가 몇 건 있는지 저장
multicase_df = nowon_cars[nowon_cars['신청대수'] != 1].copy()
multicase_count = multicase_df.shape[0]
multicase_count

1

In [13]:
# 멀티케이스의 각 row = Series
multicase_df.iloc[0]

지급일자                               2022-07-14
차종       아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용
신청대수                                        2
신청자명                               경성자동차교통(주)
주소                      서울특별시 노원구 동일로 1047 .
총액                                       2400
국비                                       1800
도비                                          0
시비                                        400
추가                                        200
차량번호                     서울33바1299\n서울33바1266
차대번호     KMHKL81AFNU110018\nKMHKL81AFNU109942
차량등록일                  2022-06-29\n2022-06-29
Name: 720, dtype: object

In [14]:
for k in range(multicase_count):
    # loc(index이름) 찾기
    print(f"loc = {multicase_df.index[k]}")

    # iloc(index숫자) 찾기 : 위에서 720(loc)이 나왔다면 이것이 몇번째 인덱스(29)인지 확인한다.
    print(f"iloc = {nowon_cars.index.get_indexer(multicase_df.index)[k]}")

loc = 720
iloc = 29

In [15]:
# 만약 나온 게 있다면 ==> 1개 행에 신청 대수가 2대 이상인 경우 처리 II
duplicated_df_list = []
for j in range(0, multicase_count):
    
    original_row = multicase_df.iloc[j].copy()    # 기준 행 = Series
    original_row_count = original_row['신청대수']
    original_row_iloc = nowon_cars.index.get_indexer(multicase_df.index)[j]

    nums = []
    vins = []
    regs = []

    nums = original_row['차량번호'].split()
    vins = original_row['차대번호'].split()
    regs = original_row['차량등록일'].split()

    original_row['신청대수'] = int(original_row['신청대수'] / original_row_count)
    original_row['총액'] = int(original_row['총액'] / original_row_count)
    original_row['국비'] = int(original_row['국비'] / original_row_count)
    original_row['도비'] = int(original_row['도비'] / original_row_count)
    original_row['시비'] = int(original_row['시비'] / original_row_count)
    original_row['추가'] = int(original_row['추가'] / original_row_count)

    original_row['차량번호'] = nums[0]
    original_row['차대번호'] = vins[0]
    original_row['차량등록일'] = regs[0]


    case_processed_df = original_row
    for i in range(1, original_row_count):
        temp_row = original_row.copy()
        temp_row['차량번호'] = nums[i]
        temp_row['차대번호'] = vins[i]
        temp_row['차량등록일'] = regs[i]
        case_processed_df = pd.concat([case_processed_df, temp_row], axis=1, ignore_index=True)

    # 원본 행 + 분리된 행 = 멀티케이스 1건당 새로운 1개의 DataFrame
    case_processed_df = case_processed_df.T
    duplicated_df_list.append(case_processed_df)
    print(case_processed_df)
    
    # 원본에서 기준행 1개 지우기
    nowon_cars.drop(multicase_df.index[j], inplace=True)


# nowon_cars에 삽입    
for m in range(0, multicase_count):
    nowon_cars = pd.concat([nowon_cars, duplicated_df_list[m]], axis=0, ignore_index=True)

nowon_cars

         지급일자                                    차종 신청대수        신청자명  \
0  2022-07-14  아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용    1  경성자동차교통(주)
1  2022-07-14  아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용    1  경성자동차교통(주)

                      주소    총액   국비 도비   시비   추가       차량번호  \
0  서울특별시 노원구 동일로 1047 .   1200  900  0  200  100  서울33바1299
1  서울특별시 노원구 동일로 1047 .   1200  900  0  200  100  서울33바1266

                차대번호       차량등록일
0  KMHKL81AFNU110018  2022-06-29
1  KMHKL81AFNU109942  2022-06-29

,지급일자,차종,신청대수,신청자명,주소,총액,국비,도비,시비,추가,차량번호,차대번호,차량등록일
0,2022-07-25,GV60 스탠다드 2WD 19인치 / 일반승용,1,윤형도,서울특별시 노원구 중계로 230 506동 304호,450,350,0,100,0,05도5584,KMTKB81AFNU007485,2022-07-14
1,2022-07-14,니로 플러스 / 일반승용,1,구본성,서울특별시 노원구 동일로 1776 2층,900,700,0,200,0,서울32자1527,KNAA381GFPT001397,2022-07-04
2,2022-07-25,The all-new Kia Niro EV / 일반승용,1,박지원,서울특별시 노원구 한글비석로 479 103동 1301호,900,700,0,200,0,58서4791,KNACR811FPA007727,2022-07-08
3,2022-07-25,GV60 스탠다드 2WD 19인치 / 일반승용,1,이진하,서울특별시 노원구 공릉로 351 2동1109호,450,350,0,100,0,37모9421,KMTKB81AFNU006916,2022-07-13
4,2022-07-14,니로 플러스 / 일반승용,1,함중근,서울특별시 노원구 덕릉로70가길 101 101동103호,900,700,0,200,0,서울31아6704,KNAA381GFPT000641,2022-06-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2022-07-11,봉고Ⅲ 전기차 / 화물(소형),1,박용현,서울특별시 노원구 중계로14다길 2 3층,2000,1400,0,600,0,88루0156,KNFSTZ7NFNK024165,2022-06-27
62,2022-07-29,넥쏘 수소연료전지차,1,김보영,서울특별시 노원구 동일로239길 68 101동 1104호,3250,2250,0,1000,0,43더8373,KMHJ8816FPU027999,2022-07-19
63,2022-07-19,넥쏘 수소연료전지차,1,이승현,서울특별시 노원구 마들로 111 25동 408호,3250,2250,0,1000,0,52머4761,KMHJ8816FPU027428,2022-06-21
64,2022-07-14,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,경성자동차교통(주),서울특별시 노원구 동일로 1047 .,1200,900,0,200,100,서울33바1299,KMHKL81AFNU110018,2022-06-29
65,2022-07-14,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,경성자동차교통(주),서울특별시 노원구 동일로 1047 .,1200,900,0,200,100,서울33바1266,KMHKL81AFNU109942,2022-06-29

In [12]:
# 신청 대수가 2대 이상인 경우 나오는지 검증
nowon_cars[nowon_cars['신청대수'] != 1]

Empty DataFrame
Columns: [지급일자, 차종, 신청대수, 신청자명, 주소, 총액, 국비, 도비, 시비, 추가, 차량번호, 차대번호, 차량등록일]
Index: []

### 한줄에 여러대(멀티케이스) 존재하는 경우 ==> 처리 끝

In [13]:
# 도비가 0이 아닌 비정상적인 경우를 걸러내기(서울시는 도비가 없음)
# ==> 아무것도 나오지 않아야 정상
nowon_cars[nowon_cars['도비'] != 0]

Empty DataFrame
Columns: [지급일자, 차종, 신청대수, 신청자명, 주소, 총액, 국비, 도비, 시비, 추가, 차량번호, 차대번호, 차량등록일]
Index: []

In [14]:
# 도비는 모두 0이므로 열을 지운다
nowon_cars = nowon_cars.drop(['도비'], axis=1)
nowon_cars

,지급일자,차종,신청대수,신청자명,주소,총액,국비,시비,추가,차량번호,차대번호,차량등록일
0,2022-08-31,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 23MY / 일반승용,1,송세용,서울특별시 노원구 동일로 1776 2층,1200,900,200,100,서울31바2052,KMHKL81EFPU118225,2022-08-19
47,2022-08-31,MINI Cooper SE / 일반승용,1,남찬미,서울특별시 노원구 공릉로59길 25 702동 402호,735,572,163,0,59무6047,WMW11DJ00P2S89769,2022-08-11
111,2022-08-31,Model Y Long Range 50 / 일반승용,1,유환기,서울특별시 노원구 상계로3길 50 102동 101호,405,315,90,0,38우1642,7SAYGDEE5NF497018,2022-08-10
126,2022-08-31,Model 3 RWD 100 / 일반승용,1,유지수,서울특별시 노원구 한글비석로14길 8 209동 205호,810,630,180,0,12가8293,5YJ3E1EA7NF303680,2022-08-10
178,2022-08-31,Model Y Long Range 50 / 일반승용,1,이혜숙,서울특별시 노원구 동일로246길 39 102동 603호,405,315,90,0,47어7257,7SAYGDEE9NF498012,2022-08-11
198,2022-08-31,니로 플러스 / 일반승용,1,김익중,서울특별시 노원구 노원로 564 1009동406호,900,700,200,0,서울31아6898,KNAA381GFPT002639,2022-08-02
223,2022-08-31,Model Y Long Range 50 / 일반승용,1,남형석,서울특별시 노원구 마들로 59 16동 703호,405,315,90,0,46오6161,7SAYGDEE9NF497670,2022-08-11
269,2022-08-31,Model Y Long Range 50 / 일반승용,1,김민우,서울특별시 노원구 상계로 193-14 101동 406호,405,315,90,0,37루1110,7SAYGDEE1NF498649,2022-08-17
370,2022-08-08,아이오닉5 2WD 롱레인지 20인치 / 일반승용,1,조성우,서울특별시 노원구 공릉로 213 106동1904호,900,700,200,0,05도6285,KMHKR81AFNU115537,2022-07-29
475,2022-08-31,EV6 롱레인지 2WD 19인치 / 일반승용,1,강희상,서울특별시 노원구 한글비석로52길 66 101동1111호,900,700,200,0,05도5817,KNAC381AFNA078777,2022-07-27
501,2022-08-01,니로 플러스 / 일반승용,1,이연호,서울특별시 노원구 공릉로46길 19 106동 402호,900,700,200,0,서울31자1716,KNAA381GFPT002232,2022-07-22
532,2022-08-01,EV6 롱레인지 4WD 19인치 / 일반승용,1,조영호,서울특별시 노원구 마들로 111 27동1101호,900,700,200,0,05도6001,KNAC381CPNA076539,2022-07-18
555,2022-08-08,Electrified GV70 AWD 20인치 / 일반승용,1,김효천,서울특별시 노원구 덕릉로94가길 20 203동 2001호,426,332,94,0,28어0574,KMTMA811PNU002203,2022-07-26
573,2022-08-01,EV6 롱레인지 2WD 19인치 / 일반승용,1,문성민,서울특별시 노원구 동일로245길 162 109동 604허,900,700,200,0,09구3282,KNAC281AFNA074087,2022-07-20
574,2022-08-01,MINI Cooper SE / 일반승용,1,정우진,서울특별시 노원구 덕릉로 517 101동 1303호,735,572,163,0,06어1508,WMW11DJ04P2S83974,2022-07-22
594,2022-08-01,니로 플러스 / 일반승용,1,김종수,서울특별시 노원구 마들로 127 34동1402호,900,700,200,0,서울32자6092,KNAA381GFPT001756,2022-07-21
595,2022-08-08,볼보 XC40 Recharge twin / 일반승용,1,강용두,서울특별시 노원구 마들로 127 33동1004호,326,254,72,0,23다9152,YV1XZEDAEN2771620,2022-07-22
664,2022-08-31,GV60 스탠다드 2WD 19인치 / 일반승용,1,김장호,서울특별시 노원구 누원로 18 403동 901호,450,350,100,0,50나8881,KMTKB81AFNU008054,2022-08-05
667,2022-08-31,EV6 롱레인지 4WD 20인치 / 일반승용,1,최창익,서울특별시 노원구 동일로175길 38 101동 903호,900,700,200,0,22어6807,KNAC581CPNA081902,2022-08-12
713,2022-08-08,EV6 롱레인지 2WD 20인치 / 일반승용,1,김명희,서울특별시 노원구 동일로245길 162 102동 803호,900,700,200,0,22어6667,KNAC381AFNA079053,2022-07-27
741,2022-08-08,GV60 스탠다드 2WD 19인치 / 일반승용,1,유태욱,서울특별시 노원구 중계로 195 105동105호,450,350,100,0,01러7769,KMTKB81AFNU007943,2022-07-29
749,2022-08-01,아이오닉5 AWD 롱레인지 19인치 / 일반승용,1,최연주,서울특별시 노원구 노원로18길 19 207동1504호,894,696,198,0,43더8195,KMHKN81CPNU114461,2022-07-19
755,2022-08-01,아이오닉5 AWD 롱레인지 20인치 / 일반승용,1,김철구,서울특별시 노원구 중계로8길 20 105동1204호,874,680,194,0,05도6123,KMHKR81CPNU116096,2022-07-21
803,2022-08-31,아이오닉5 AWD 롱레인지 19인치23MY / 일반승용,1,조금보,서울특별시 노원구 동일로 1776 2층,1200,900,200,100,서울31자8265,KMHKL81FPPU118212,2022-08-10
811,2022-08-08,니로 플러스 / 일반승용,1,김광영,서울특별시 노원구 한글비석로24라길 76-9 1층,1200,900,200,100,서울31사4530,KNAA381GFPT002461,2022-07-26
817,2022-08-31,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 23MY / 일반승용,1,김경중,서울특별시 노원구 동일로227길 86 1607동601호,1200,900,200,100,서울32아3217,KMHKL81EFPU123802,2022-08-19
827,2022-08-31,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 23MY / 일반승용,1,이은영,서울특별시 노원구 동일로215길 48 322동 1001호,1200,900,200,100,서울31사8628,KMHKL81EFPU120277,2022-08-01
840,2022-08-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 23MY / 일반승용,1,신윤섭,서울특별시 노원구 동일로 1776 2층,1200,900,200,100,서울32자5592,KMHKL81EFPU118700,2022-07-27
854,2022-08-31,아이오닉5 2WD 롱레인지 19인치 23MY / 일반승용,1,김영호,서울특별시 노원구 동일로208길 20 210동 304호,1200,900,200,100,서울31자8802,KMHKL81EFPU120874,2022-08-03
863,2022-08-31,아이오닉5 2WD 롱레인지 19인치 23MY / 일반승용,1,김명식,서울특별시 노원구 노원로28길 15 101동2209호,1200,900,200,100,서울32바4139,KMHKL81EFPU118860,2022-07-29
888,2022-08-31,아이오닉5 2WD 롱레인지 19인치 23MY / 일반승용,1,장준호,서울특별시 노원구 동일로 1776 2층,1200,900,200,100,서울31아5750,KMHKL81EFPU121138,2022-08-10
925,2022-08-05,MASADA 2밴 / 화물(소형),1,한정아,서울특별시 노원구 노원로30길 32 102동 302호,2140,1540,600,0,84수8230,LVPRPB4B8NC891104,2022-07-14
957,2022-08-05,포터Ⅱ 일렉트릭 / 화물(소형),1,황종순,서울특별시 노원구 덕릉로126라길 18-1 지층,2000,1400,600,0,84마7785,KMFZCZ7NFNU036613,2022-07-20
970,2022-08-05,포터Ⅱ 일렉트릭 / 화물(소형),1,김명희,서울특별시 노원구 덕릉로 718 101동 103호,2000,1400,600,0,84마7829,KMFZSZ7NFNU034825,2022-07-19

In [15]:
# 이제 확인이 끝났으므로 불필요한 '차종', '신청대수', '주소' 열을 지운다.
nowon_cars = nowon_cars.drop(['차종', '신청대수', '주소'], axis=1)
nowon_cars

,지급일자,신청자명,총액,국비,시비,추가,차량번호,차대번호,차량등록일
0,2022-08-31,송세용,1200,900,200,100,서울31바2052,KMHKL81EFPU118225,2022-08-19
47,2022-08-31,남찬미,735,572,163,0,59무6047,WMW11DJ00P2S89769,2022-08-11
111,2022-08-31,유환기,405,315,90,0,38우1642,7SAYGDEE5NF497018,2022-08-10
126,2022-08-31,유지수,810,630,180,0,12가8293,5YJ3E1EA7NF303680,2022-08-10
178,2022-08-31,이혜숙,405,315,90,0,47어7257,7SAYGDEE9NF498012,2022-08-11
198,2022-08-31,김익중,900,700,200,0,서울31아6898,KNAA381GFPT002639,2022-08-02
223,2022-08-31,남형석,405,315,90,0,46오6161,7SAYGDEE9NF497670,2022-08-11
269,2022-08-31,김민우,405,315,90,0,37루1110,7SAYGDEE1NF498649,2022-08-17
370,2022-08-08,조성우,900,700,200,0,05도6285,KMHKR81AFNU115537,2022-07-29
475,2022-08-31,강희상,900,700,200,0,05도5817,KNAC381AFNA078777,2022-07-27
501,2022-08-01,이연호,900,700,200,0,서울31자1716,KNAA381GFPT002232,2022-07-22
532,2022-08-01,조영호,900,700,200,0,05도6001,KNAC381CPNA076539,2022-07-18
555,2022-08-08,김효천,426,332,94,0,28어0574,KMTMA811PNU002203,2022-07-26
573,2022-08-01,문성민,900,700,200,0,09구3282,KNAC281AFNA074087,2022-07-20
574,2022-08-01,정우진,735,572,163,0,06어1508,WMW11DJ04P2S83974,2022-07-22
594,2022-08-01,김종수,900,700,200,0,서울32자6092,KNAA381GFPT001756,2022-07-21
595,2022-08-08,강용두,326,254,72,0,23다9152,YV1XZEDAEN2771620,2022-07-22
664,2022-08-31,김장호,450,350,100,0,50나8881,KMTKB81AFNU008054,2022-08-05
667,2022-08-31,최창익,900,700,200,0,22어6807,KNAC581CPNA081902,2022-08-12
713,2022-08-08,김명희,900,700,200,0,22어6667,KNAC381AFNA079053,2022-07-27
741,2022-08-08,유태욱,450,350,100,0,01러7769,KMTKB81AFNU007943,2022-07-29
749,2022-08-01,최연주,894,696,198,0,43더8195,KMHKN81CPNU114461,2022-07-19
755,2022-08-01,김철구,874,680,194,0,05도6123,KMHKR81CPNU116096,2022-07-21
803,2022-08-31,조금보,1200,900,200,100,서울31자8265,KMHKL81FPPU118212,2022-08-10
811,2022-08-08,김광영,1200,900,200,100,서울31사4530,KNAA381GFPT002461,2022-07-26
817,2022-08-31,김경중,1200,900,200,100,서울32아3217,KMHKL81EFPU123802,2022-08-19
827,2022-08-31,이은영,1200,900,200,100,서울31사8628,KMHKL81EFPU120277,2022-08-01
840,2022-08-08,신윤섭,1200,900,200,100,서울32자5592,KMHKL81EFPU118700,2022-07-27
854,2022-08-31,김영호,1200,900,200,100,서울31자8802,KMHKL81EFPU120874,2022-08-03
863,2022-08-31,김명식,1200,900,200,100,서울32바4139,KMHKL81EFPU118860,2022-07-29
888,2022-08-31,장준호,1200,900,200,100,서울31아5750,KMHKL81EFPU121138,2022-08-10
925,2022-08-05,한정아,2140,1540,600,0,84수8230,LVPRPB4B8NC891104,2022-07-14
957,2022-08-05,황종순,2000,1400,600,0,84마7785,KMFZCZ7NFNU036613,2022-07-20
970,2022-08-05,김명희,2000,1400,600,0,84마7829,KMFZSZ7NFNU034825,2022-07-19

In [16]:
nowon_cars

,지급일자,신청자명,총액,국비,시비,추가,차량번호,차대번호,차량등록일
0,2022-08-31,송세용,1200,900,200,100,서울31바2052,KMHKL81EFPU118225,2022-08-19
47,2022-08-31,남찬미,735,572,163,0,59무6047,WMW11DJ00P2S89769,2022-08-11
111,2022-08-31,유환기,405,315,90,0,38우1642,7SAYGDEE5NF497018,2022-08-10
126,2022-08-31,유지수,810,630,180,0,12가8293,5YJ3E1EA7NF303680,2022-08-10
178,2022-08-31,이혜숙,405,315,90,0,47어7257,7SAYGDEE9NF498012,2022-08-11
198,2022-08-31,김익중,900,700,200,0,서울31아6898,KNAA381GFPT002639,2022-08-02
223,2022-08-31,남형석,405,315,90,0,46오6161,7SAYGDEE9NF497670,2022-08-11
269,2022-08-31,김민우,405,315,90,0,37루1110,7SAYGDEE1NF498649,2022-08-17
370,2022-08-08,조성우,900,700,200,0,05도6285,KMHKR81AFNU115537,2022-07-29
475,2022-08-31,강희상,900,700,200,0,05도5817,KNAC381AFNA078777,2022-07-27
501,2022-08-01,이연호,900,700,200,0,서울31자1716,KNAA381GFPT002232,2022-07-22
532,2022-08-01,조영호,900,700,200,0,05도6001,KNAC381CPNA076539,2022-07-18
555,2022-08-08,김효천,426,332,94,0,28어0574,KMTMA811PNU002203,2022-07-26
573,2022-08-01,문성민,900,700,200,0,09구3282,KNAC281AFNA074087,2022-07-20
574,2022-08-01,정우진,735,572,163,0,06어1508,WMW11DJ04P2S83974,2022-07-22
594,2022-08-01,김종수,900,700,200,0,서울32자6092,KNAA381GFPT001756,2022-07-21
595,2022-08-08,강용두,326,254,72,0,23다9152,YV1XZEDAEN2771620,2022-07-22
664,2022-08-31,김장호,450,350,100,0,50나8881,KMTKB81AFNU008054,2022-08-05
667,2022-08-31,최창익,900,700,200,0,22어6807,KNAC581CPNA081902,2022-08-12
713,2022-08-08,김명희,900,700,200,0,22어6667,KNAC381AFNA079053,2022-07-27
741,2022-08-08,유태욱,450,350,100,0,01러7769,KMTKB81AFNU007943,2022-07-29
749,2022-08-01,최연주,894,696,198,0,43더8195,KMHKN81CPNU114461,2022-07-19
755,2022-08-01,김철구,874,680,194,0,05도6123,KMHKR81CPNU116096,2022-07-21
803,2022-08-31,조금보,1200,900,200,100,서울31자8265,KMHKL81FPPU118212,2022-08-10
811,2022-08-08,김광영,1200,900,200,100,서울31사4530,KNAA381GFPT002461,2022-07-26
817,2022-08-31,김경중,1200,900,200,100,서울32아3217,KMHKL81EFPU123802,2022-08-19
827,2022-08-31,이은영,1200,900,200,100,서울31사8628,KMHKL81EFPU120277,2022-08-01
840,2022-08-08,신윤섭,1200,900,200,100,서울32자5592,KMHKL81EFPU118700,2022-07-27
854,2022-08-31,김영호,1200,900,200,100,서울31자8802,KMHKL81EFPU120874,2022-08-03
863,2022-08-31,김명식,1200,900,200,100,서울32바4139,KMHKL81EFPU118860,2022-07-29
888,2022-08-31,장준호,1200,900,200,100,서울31아5750,KMHKL81EFPU121138,2022-08-10
925,2022-08-05,한정아,2140,1540,600,0,84수8230,LVPRPB4B8NC891104,2022-07-14
957,2022-08-05,황종순,2000,1400,600,0,84마7785,KMFZCZ7NFNU036613,2022-07-20
970,2022-08-05,김명희,2000,1400,600,0,84마7829,KMFZSZ7NFNU034825,2022-07-19

In [17]:
# 총액 = 국비 + 시비 + 추가 ==> 금액이 맞는지 확인 ==> 나오는 게 없어야 정상
nowon_cars[nowon_cars['총액'] != nowon_cars['국비'] + nowon_cars['시비'] + nowon_cars['추가']]

Empty DataFrame
Columns: [지급일자, 신청자명, 총액, 국비, 시비, 추가, 차량번호, 차대번호, 차량등록일]
Index: []

In [18]:
# 특기사항이 화면에 모두 출력될 수 있도록 열의 최대출력 길이 변경
pd.set_option('display.max_colwidth', 200)

# 인덱스(행 이름) 0부터 정렬 + dataframe 이름 변경
df = nowon_cars.reset_index(drop=True)
df

,지급일자,신청자명,총액,국비,시비,추가,차량번호,차대번호,차량등록일
0,2022-08-31,송세용,1200,900,200,100,서울31바2052,KMHKL81EFPU118225,2022-08-19
1,2022-08-31,남찬미,735,572,163,0,59무6047,WMW11DJ00P2S89769,2022-08-11
2,2022-08-31,유환기,405,315,90,0,38우1642,7SAYGDEE5NF497018,2022-08-10
3,2022-08-31,유지수,810,630,180,0,12가8293,5YJ3E1EA7NF303680,2022-08-10
4,2022-08-31,이혜숙,405,315,90,0,47어7257,7SAYGDEE9NF498012,2022-08-11
5,2022-08-31,김익중,900,700,200,0,서울31아6898,KNAA381GFPT002639,2022-08-02
6,2022-08-31,남형석,405,315,90,0,46오6161,7SAYGDEE9NF497670,2022-08-11
7,2022-08-31,김민우,405,315,90,0,37루1110,7SAYGDEE1NF498649,2022-08-17
8,2022-08-08,조성우,900,700,200,0,05도6285,KMHKR81AFNU115537,2022-07-29
9,2022-08-31,강희상,900,700,200,0,05도5817,KNAC381AFNA078777,2022-07-27
10,2022-08-01,이연호,900,700,200,0,서울31자1716,KNAA381GFPT002232,2022-07-22
11,2022-08-01,조영호,900,700,200,0,05도6001,KNAC381CPNA076539,2022-07-18
12,2022-08-08,김효천,426,332,94,0,28어0574,KMTMA811PNU002203,2022-07-26
13,2022-08-01,문성민,900,700,200,0,09구3282,KNAC281AFNA074087,2022-07-20
14,2022-08-01,정우진,735,572,163,0,06어1508,WMW11DJ04P2S83974,2022-07-22
15,2022-08-01,김종수,900,700,200,0,서울32자6092,KNAA381GFPT001756,2022-07-21
16,2022-08-08,강용두,326,254,72,0,23다9152,YV1XZEDAEN2771620,2022-07-22
17,2022-08-31,김장호,450,350,100,0,50나8881,KMTKB81AFNU008054,2022-08-05
18,2022-08-31,최창익,900,700,200,0,22어6807,KNAC581CPNA081902,2022-08-12
19,2022-08-08,김명희,900,700,200,0,22어6667,KNAC381AFNA079053,2022-07-27
20,2022-08-08,유태욱,450,350,100,0,01러7769,KMTKB81AFNU007943,2022-07-29
21,2022-08-01,최연주,894,696,198,0,43더8195,KMHKN81CPNU114461,2022-07-19
22,2022-08-01,김철구,874,680,194,0,05도6123,KMHKR81CPNU116096,2022-07-21
23,2022-08-31,조금보,1200,900,200,100,서울31자8265,KMHKL81FPPU118212,2022-08-10
24,2022-08-08,김광영,1200,900,200,100,서울31사4530,KNAA381GFPT002461,2022-07-26
25,2022-08-31,김경중,1200,900,200,100,서울32아3217,KMHKL81EFPU123802,2022-08-19
26,2022-08-31,이은영,1200,900,200,100,서울31사8628,KMHKL81EFPU120277,2022-08-01
27,2022-08-08,신윤섭,1200,900,200,100,서울32자5592,KMHKL81EFPU118700,2022-07-27
28,2022-08-31,김영호,1200,900,200,100,서울31자8802,KMHKL81EFPU120874,2022-08-03
29,2022-08-31,김명식,1200,900,200,100,서울32바4139,KMHKL81EFPU118860,2022-07-29
30,2022-08-31,장준호,1200,900,200,100,서울31아5750,KMHKL81EFPU121138,2022-08-10
31,2022-08-05,한정아,2140,1540,600,0,84수8230,LVPRPB4B8NC891104,2022-07-14
32,2022-08-05,황종순,2000,1400,600,0,84마7785,KMFZCZ7NFNU036613,2022-07-20
33,2022-08-05,김명희,2000,1400,600,0,84마7829,KMFZSZ7NFNU034825,2022-07-19

In [19]:
df['지급일자'] = df['지급일자'].apply(lambda x: x[:4] + '.' + x[5:7] + '.' + x[8:])
df['차량등록일'] = df['차량등록일'].apply(lambda x: x[:4] + '.' + x[5:7] + '.' + x[8:])
df

,지급일자,신청자명,총액,국비,시비,추가,차량번호,차대번호,차량등록일
0,2022.08.31,송세용,1200,900,200,100,서울31바2052,KMHKL81EFPU118225,2022.08.19
1,2022.08.31,남찬미,735,572,163,0,59무6047,WMW11DJ00P2S89769,2022.08.11
2,2022.08.31,유환기,405,315,90,0,38우1642,7SAYGDEE5NF497018,2022.08.10
3,2022.08.31,유지수,810,630,180,0,12가8293,5YJ3E1EA7NF303680,2022.08.10
4,2022.08.31,이혜숙,405,315,90,0,47어7257,7SAYGDEE9NF498012,2022.08.11
5,2022.08.31,김익중,900,700,200,0,서울31아6898,KNAA381GFPT002639,2022.08.02
6,2022.08.31,남형석,405,315,90,0,46오6161,7SAYGDEE9NF497670,2022.08.11
7,2022.08.31,김민우,405,315,90,0,37루1110,7SAYGDEE1NF498649,2022.08.17
8,2022.08.08,조성우,900,700,200,0,05도6285,KMHKR81AFNU115537,2022.07.29
9,2022.08.31,강희상,900,700,200,0,05도5817,KNAC381AFNA078777,2022.07.27
10,2022.08.01,이연호,900,700,200,0,서울31자1716,KNAA381GFPT002232,2022.07.22
11,2022.08.01,조영호,900,700,200,0,05도6001,KNAC381CPNA076539,2022.07.18
12,2022.08.08,김효천,426,332,94,0,28어0574,KMTMA811PNU002203,2022.07.26
13,2022.08.01,문성민,900,700,200,0,09구3282,KNAC281AFNA074087,2022.07.20
14,2022.08.01,정우진,735,572,163,0,06어1508,WMW11DJ04P2S83974,2022.07.22
15,2022.08.01,김종수,900,700,200,0,서울32자6092,KNAA381GFPT001756,2022.07.21
16,2022.08.08,강용두,326,254,72,0,23다9152,YV1XZEDAEN2771620,2022.07.22
17,2022.08.31,김장호,450,350,100,0,50나8881,KMTKB81AFNU008054,2022.08.05
18,2022.08.31,최창익,900,700,200,0,22어6807,KNAC581CPNA081902,2022.08.12
19,2022.08.08,김명희,900,700,200,0,22어6667,KNAC381AFNA079053,2022.07.27
20,2022.08.08,유태욱,450,350,100,0,01러7769,KMTKB81AFNU007943,2022.07.29
21,2022.08.01,최연주,894,696,198,0,43더8195,KMHKN81CPNU114461,2022.07.19
22,2022.08.01,김철구,874,680,194,0,05도6123,KMHKR81CPNU116096,2022.07.21
23,2022.08.31,조금보,1200,900,200,100,서울31자8265,KMHKL81FPPU118212,2022.08.10
24,2022.08.08,김광영,1200,900,200,100,서울31사4530,KNAA381GFPT002461,2022.07.26
25,2022.08.31,김경중,1200,900,200,100,서울32아3217,KMHKL81EFPU123802,2022.08.19
26,2022.08.31,이은영,1200,900,200,100,서울31사8628,KMHKL81EFPU120277,2022.08.01
27,2022.08.08,신윤섭,1200,900,200,100,서울32자5592,KMHKL81EFPU118700,2022.07.27
28,2022.08.31,김영호,1200,900,200,100,서울31자8802,KMHKL81EFPU120874,2022.08.03
29,2022.08.31,김명식,1200,900,200,100,서울32바4139,KMHKL81EFPU118860,2022.07.29
30,2022.08.31,장준호,1200,900,200,100,서울31아5750,KMHKL81EFPU121138,2022.08.10
31,2022.08.05,한정아,2140,1540,600,0,84수8230,LVPRPB4B8NC891104,2022.07.14
32,2022.08.05,황종순,2000,1400,600,0,84마7785,KMFZCZ7NFNU036613,2022.07.20
33,2022.08.05,김명희,2000,1400,600,0,84마7829,KMFZSZ7NFNU034825,2022.07.19

In [20]:
# 특기사항 입력
# 예: 서울특별시, 전기차 구매보조금 339만원(국비 264만원, 시비 75만원, 지급일자 2022.5.24.) 서울시 기후변화대응과-24031(2022.06.17.)
df['특기사항'] = "서울특별시, 전기차 구매보조금 " + (df['총액']).astype('str') + "만원 (국비 " + (df['국비']).astype('str') + "만원, 시비 " + (df['시비'] + df['추가']).astype('str') + "만원, 지급일자 " + df['지급일자'] + ") " + doc_num
df

,지급일자,신청자명,총액,국비,시비,추가,차량번호,차대번호,차량등록일,특기사항
0,2022.08.31,송세용,1200,900,200,100,서울31바2052,KMHKL81EFPU118225,2022.08.19,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
1,2022.08.31,남찬미,735,572,163,0,59무6047,WMW11DJ00P2S89769,2022.08.11,"서울특별시, 전기차 구매보조금 735만원 (국비 572만원, 시비 163만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
2,2022.08.31,유환기,405,315,90,0,38우1642,7SAYGDEE5NF497018,2022.08.10,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
3,2022.08.31,유지수,810,630,180,0,12가8293,5YJ3E1EA7NF303680,2022.08.10,"서울특별시, 전기차 구매보조금 810만원 (국비 630만원, 시비 180만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
4,2022.08.31,이혜숙,405,315,90,0,47어7257,7SAYGDEE9NF498012,2022.08.11,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
5,2022.08.31,김익중,900,700,200,0,서울31아6898,KNAA381GFPT002639,2022.08.02,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
6,2022.08.31,남형석,405,315,90,0,46오6161,7SAYGDEE9NF497670,2022.08.11,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
7,2022.08.31,김민우,405,315,90,0,37루1110,7SAYGDEE1NF498649,2022.08.17,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
8,2022.08.08,조성우,900,700,200,0,05도6285,KMHKR81AFNU115537,2022.07.29,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022.08.08) 서울시 친환경차량과-1211(2022.09.20.)"
9,2022.08.31,강희상,900,700,200,0,05도5817,KNAC381AFNA078777,2022.07.27,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
10,2022.08.01,이연호,900,700,200,0,서울31자1716,KNAA381GFPT002232,2022.07.22,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022.08.01) 서울시 친환경차량과-1211(2022.09.20.)"
11,2022.08.01,조영호,900,700,200,0,05도6001,KNAC381CPNA076539,2022.07.18,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022.08.01) 서울시 친환경차량과-1211(2022.09.20.)"
12,2022.08.08,김효천,426,332,94,0,28어0574,KMTMA811PNU002203,2022.07.26,"서울특별시, 전기차 구매보조금 426만원 (국비 332만원, 시비 94만원, 지급일자 2022.08.08) 서울시 친환경차량과-1211(2022.09.20.)"
13,2022.08.01,문성민,900,700,200,0,09구3282,KNAC281AFNA074087,2022.07.20,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022.08.01) 서울시 친환경차량과-1211(2022.09.20.)"
14,2022.08.01,정우진,735,572,163,0,06어1508,WMW11DJ04P2S83974,2022.07.22,"서울특별시, 전기차 구매보조금 735만원 (국비 572만원, 시비 163만원, 지급일자 2022.08.01) 서울시 친환경차량과-1211(2022.09.20.)"
15,2022.08.01,김종수,900,700,200,0,서울32자6092,KNAA381GFPT001756,2022.07.21,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022.08.01) 서울시 친환경차량과-1211(2022.09.20.)"
16,2022.08.08,강용두,326,254,72,0,23다9152,YV1XZEDAEN2771620,2022.07.22,"서울특별시, 전기차 구매보조금 326만원 (국비 254만원, 시비 72만원, 지급일자 2022.08.08) 서울시 친환경차량과-1211(2022.09.20.)"
17,2022.08.31,김장호,450,350,100,0,50나8881,KMTKB81AFNU008054,2022.08.05,"서울특별시, 전기차 구매보조금 450만원 (국비 350만원, 시비 100만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
18,2022.08.31,최창익,900,700,200,0,22어6807,KNAC581CPNA081902,2022.08.12,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
19,2022.08.08,김명희,900,700,200,0,22어6667,KNAC381AFNA079053,2022.07.27,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022.08.08) 서울시 친환경차량과-1211(2022.09.20.)"
20,2022.08.08,유태욱,450,350,100,0,01러7769,KMTKB81AFNU007943,2022.07.29,"서울특별시, 전기차 구매보조금 450만원 (국비 350만원, 시비 100만원, 지급일자 2022.08.08) 서울시 친환경차량과-1211(2022.09.20.)"
21,2022.08.01,최연주,894,696,198,0,43더8195,KMHKN81CPNU114461,2022.07.19,"서울특별시, 전기차 구매보조금 894만원 (국비 696만원, 시비 198만원, 지급일자 2022.08.01) 서울시 친환경차량과-1211(2022.09.20.)"
22,2022.08.01,김철구,874,680,194,0,05도6123,KMHKR81CPNU116096,2022.07.21,"서울특별시, 전기차 구매보조금 874만원 (국비 680만원, 시비 194만원, 지급일자 2022.08.01) 서울시 친환경차량과-1211(2022.09.20.)"
23,2022.08.31,조금보,1200,900,200,100,서울31자8265,KMHKL81FPPU118212,2022.08.10,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
24,2022.08.08,김광영,1200,900,200,100,서울31사4530,KNAA381GFPT002461,2022.07.26,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022.08.08) 서울시 친환경차량과-1211(2022.09.20.)"
25,2022.08.31,김경중,1200,900,200,100,서울32아3217,KMHKL81EFPU123802,2022.08.19,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
26,2022.08.31,이은영,1200,900,200,100,서울31사8628,KMHKL81EFPU120277,2022.08.01,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
27,2022.08.08,신윤섭,1200,900,200,100,서울32자5592,KMHKL81EFPU118700,2022.07.27,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022.08.08) 서울시 친환경차량과-1211(2022.09.20.)"
28,2022.08.31,김영호,1200,900,200,100,서울31자8802,KMHKL81EFPU120874,2022.08.03,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
29,2022.08.31,김명식,1200,900,200,100,서울32바4139,KMHKL81EFPU118860,2022.07.29,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
30,2022.08.31,장준호,1200,900,200,100,서울31아5750,KMHKL81EFPU121138,2022.08.10,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022.08.31) 서울시 친환경차량과-1211(2022.09.20.)"
31,2022.08.05,한정아,2140,1540,600,0,84수8230,LVPRPB4B8NC891104,2022.07.14,"서울특별시, 전기차 구매보조금 2140만원 (국비 1540만원, 시비 600만원, 지급일자 2022.08.05) 서울시 친환경차량과-1211(2022.09.20.)"
32,2022.08.05,황종순,2000,1400,600,0,84마7785,KMFZCZ7NFNU036613,2022.07.20,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022.08.05) 서울시 친환경차량과-1211(2022.09.20.)"
33,2022.08.05,김명희,2000,1400,600,0,84마7829,KMFZSZ7NFNU034825,2022.07.19,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022.08.05) 서울시 친환경차량과-1211(2022.09.20.)"

In [21]:
# pip install XlsxWriter

writer = pd.ExcelWriter(f"{year}_{month}_보조금_preprocessed.xlsx") 
df.to_excel(writer, sheet_name='보조금', index=False)

for column in df:
    column_length = max(df[column].astype(str).map(len).max(), len(column))
    col_idx = df.columns.get_loc(column)
    writer.sheets['보조금'].set_column(col_idx, col_idx, column_length*1.3)    # 한글 때문에 X1.3으로 열너비 늘렸다.

writer.save()

### 전처리로 만들어진 xlsx 파일 ==> 후처리에서 특기사항 입력