In [1]:
import pandas as pd

In [2]:
# 첫번째 시트 : 전기차
car1 = pd.read_excel("1.xlsx", dtype="string", header=4, sheet_name=0)
car1

,차종구분,신청\n번호,지급일자,차종,신청\n대수,신청자명,주소\n(등록주소지),신청\n총금액(만원),국비(만원),도비(만원),시비(만원),추가\n보조금(만원),차량번호,차대번호,차량출고일,차량등록일
0,전기승용,10122,2022-06-23,니로 플러스 / 일반승용,1,김명철,경기도 의정부시 흥선로82번길 27 .,900,700,0,200,0,서울31자9071,KNAA381GFPT001058,2022-06-17,2022-06-20
1,전기승용,10104,2022-06-23,Electrified GV70 AWD 19인치 / 일반승용,1,현대캐피탈주식회사,서울특별시 영등포구 의사당대로 3 .,398.5,349,0,49.5,0,26도5369,KMTMA811PNU001795,2022-06-17,2022-06-21
2,전기승용,10084,2022-06-23,iX3 M Sport / 일반승용,1,이정민,서울특별시 노원구 석계로 49 106동1002호,384,299,0,85,0,68저4780,WBY41DU07NS426522,2022-06-21,2022-06-21
3,전기승용,10042,2022-06-23,EV6 롱레인지 2WD 19인치 / 일반승용,1,김종술,서울특별시 강남구 개포로 636 4층,900,700,0,200,0,서울31사2551,KNAC281AFNA067027,2022-06-16,2022-06-17
4,전기승용,10013,2022-06-23,니로 플러스 / 일반승용,1,원태욱,서울특별시 영등포구 신풍로 77 114동 303호,900,700,0,200,0,서울31자7759,KNAA381GFPT000865,2022-06-14,2022-06-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,전기버스,44,2022-06-21,하이퍼스1609 / 승합(대형),1,종로운수(주),서울특별시 종로구 낙산길 196 208동 305호,"12,136","6,068",0,"6,068",0,서울70사5507,LKLA6E1X6NA770934,2022-04-11,2022-04-19
1201,전기버스,43,2022-06-13,하이퍼스1609 / 승합(대형),3,대상운수(주),서울특별시 영등포구 당산로41길 23 301호,"36,408","18,204",0,"18,204",0,서울71사2516 서울71사2515 서울71사2514,LKLA6E1X2NA770932 LKLA6E1X4MA769506 LKLA6E1X1N...,2022-04-15 2022-02-10 2022-02-10,2022-04-18 2022-02-17 2022-02-17
1202,전기버스,42,2022-06-13,하이퍼스1609 / 승합(대형),1,대림운수(주),서울특별시 영등포구 당산로41길 23 301호,"12,136","6,068",0,"6,068",0,서울70사8533,LKLA6E1X4NA770933,2022-04-01,2022-04-18
1203,전기버스,39,2022-06-30,스마트 9.3 / 승합(대형),2,삼양교통(주),서울특별시 강북구 삼양로173길 12 삼양교통,"28,000","14,000",0,"14,000",0,서울74사3262 서울74사3279,KM90G7ZFENABD6012 KM90G7ZFENABD6013,2022-04-07 2022-04-07,2022-04-08 2022-04-11
1204,전기버스,37,2022-06-14,카운티 일렉트릭 / 승합(중형),1,한국삭도공업(주),서울특별시 중구 소파로 83 한국삭도공업(주),"8,782","4,391",0,"4,391",0,71오7382,KMJHG19VPNC001898,2022-05-27,2022-05-31

In [3]:
# 두번째 시트 : 수소차
car2 = pd.read_excel("1.xlsx", dtype="string", header=4, sheet_name=1)
car2

,신청\n번호,지급일자,차종,신청\n대수,신청자명,주소\n(등록주소지),신청\n총금액(만원),국비(만원),도비(만원),시비(만원),추가\n보조금(만원),차량번호,차대번호,차량출고일,차량등록일
0,365,2022-06-28,넥쏘 수소연료전지차,1,마영록,서울특별시 강동구 상일로 55 117동 1401호,"3,250","2,250",0,"1,000",0,60소8380,KMHJ8816FPU026850,2022-05-31,2022-06-03
1,359,2022-06-28,넥쏘 수소연료전지차,1,문점,서울특별시 관악구 남부순환로198길 10 601호,"3,250","2,250",0,"1,000",0,45노3073,KMHJ8816FPU025883,2022-05-31,2022-06-03
2,357,2022-06-28,넥쏘 수소연료전지차,1,코원에너지서비스(주),서울특별시 강남구 남부순환로 3165 .,"3,250","2,250",0,"1,000",0,42조2483,KMHJ7816FPU026880,2022-06-02,2022-06-08
3,356,2022-06-28,넥쏘 수소연료전지차,1,코원에너지서비스(주),서울특별시 강남구 남부순환로 3165 .,"3,250","2,250",0,"1,000",0,42조2446,KMHJ7816FPU026780,2022-06-02,2022-06-08
4,355,2022-06-28,넥쏘 수소연료전지차,1,코원에너지서비스(주),서울특별시 강남구 남부순환로 3165 .,"3,250","2,250",0,"1,000",0,42조1632,KMHJ7816FPU026676,2022-06-02,2022-06-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,6,2022-06-09,넥쏘 수소연료전지차,1,김계정,"서울특별시 노원구 섬밭로 139 110동 602호 (공릉동, 공릉풍림아파트)","3,250","2,250",0,"1,000",0,39보7457,KMHJ8816FPU026015,2022-05-18,2022-05-23
139,3,2022-06-22,넥쏘 수소연료전지차,1,김은미,서울특별시 성북구 화랑로15길 4 101동 1407호,"3,250","2,250",0,"1,000",0,07다6582,KMHJ8816FPU026197,2022-05-17,2022-05-20
140,2,2022-06-22,넥쏘 수소연료전지차,1,조현정,서울특별시 용산구 이촌로87길 21 104동 702호,"3,250","2,250",0,"1,000",0,54버3040,KMHJ8816FPU025941,2022-05-18,2022-05-24
141,1,2022-06-22,넥쏘 수소연료전지차,1,티피지이엔지 주식회사,서울특별시 양천구 목동동로 293 3304,"3,250","2,250",0,"1,000",0,45노2368,KMHJ8816FPU025291,2022-05-13,2022-05-19
142,912,2022-06-08,일렉시티 FCEV,5,공항버스(주),서울특별시 강서구 개화동로8길 17 개화동,"150,000","75,000",0,"75,000",0,서울70사8163 서울70사8164 서울70사8165 서울70사8166 서울75사1682,KMJTA18YPNC001596 KMJTA18YPNC001597 KMJTA18YPN...,2022-05-23 2022-05-23 2022-05-23 2022-05-23 20...,2022-05-31 2022-05-31 2022-05-31 2022-05-31 20...

In [4]:
cars = pd.concat([car1, car2], ignore_index=True)
cars

,차종구분,신청\n번호,지급일자,차종,신청\n대수,신청자명,주소\n(등록주소지),신청\n총금액(만원),국비(만원),도비(만원),시비(만원),추가\n보조금(만원),차량번호,차대번호,차량출고일,차량등록일
0,전기승용,10122,2022-06-23,니로 플러스 / 일반승용,1,김명철,경기도 의정부시 흥선로82번길 27 .,900,700,0,200,0,서울31자9071,KNAA381GFPT001058,2022-06-17,2022-06-20
1,전기승용,10104,2022-06-23,Electrified GV70 AWD 19인치 / 일반승용,1,현대캐피탈주식회사,서울특별시 영등포구 의사당대로 3 .,398.5,349,0,49.5,0,26도5369,KMTMA811PNU001795,2022-06-17,2022-06-21
2,전기승용,10084,2022-06-23,iX3 M Sport / 일반승용,1,이정민,서울특별시 노원구 석계로 49 106동1002호,384,299,0,85,0,68저4780,WBY41DU07NS426522,2022-06-21,2022-06-21
3,전기승용,10042,2022-06-23,EV6 롱레인지 2WD 19인치 / 일반승용,1,김종술,서울특별시 강남구 개포로 636 4층,900,700,0,200,0,서울31사2551,KNAC281AFNA067027,2022-06-16,2022-06-17
4,전기승용,10013,2022-06-23,니로 플러스 / 일반승용,1,원태욱,서울특별시 영등포구 신풍로 77 114동 303호,900,700,0,200,0,서울31자7759,KNAA381GFPT000865,2022-06-14,2022-06-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1343,<NA>,6,2022-06-09,넥쏘 수소연료전지차,1,김계정,"서울특별시 노원구 섬밭로 139 110동 602호 (공릉동, 공릉풍림아파트)","3,250","2,250",0,"1,000",0,39보7457,KMHJ8816FPU026015,2022-05-18,2022-05-23
1344,<NA>,3,2022-06-22,넥쏘 수소연료전지차,1,김은미,서울특별시 성북구 화랑로15길 4 101동 1407호,"3,250","2,250",0,"1,000",0,07다6582,KMHJ8816FPU026197,2022-05-17,2022-05-20
1345,<NA>,2,2022-06-22,넥쏘 수소연료전지차,1,조현정,서울특별시 용산구 이촌로87길 21 104동 702호,"3,250","2,250",0,"1,000",0,54버3040,KMHJ8816FPU025941,2022-05-18,2022-05-24
1346,<NA>,1,2022-06-22,넥쏘 수소연료전지차,1,티피지이엔지 주식회사,서울특별시 양천구 목동동로 293 3304,"3,250","2,250",0,"1,000",0,45노2368,KMHJ8816FPU025291,2022-05-13,2022-05-19
1347,<NA>,912,2022-06-08,일렉시티 FCEV,5,공항버스(주),서울특별시 강서구 개화동로8길 17 개화동,"150,000","75,000",0,"75,000",0,서울70사8163 서울70사8164 서울70사8165 서울70사8166 서울75사1682,KMJTA18YPNC001596 KMJTA18YPNC001597 KMJTA18YPN...,2022-05-23 2022-05-23 2022-05-23 2022-05-23 20...,2022-05-31 2022-05-31 2022-05-31 2022-05-31 20...

In [5]:
# 열 이름 가져오기
cars.keys()

Index(['차종구분', '신청\n번호', '지급일자', '차종', '신청\n대수', '신청자명', '주소\n(등록주소지)',
       '신청\n총금액(만원)', '국비(만원)', '도비(만원)', '시비(만원)', '추가\n보조금(만원)', '차량번호',
       '차대번호', '차량출고일', '차량등록일'],
      dtype='object')

In [6]:
# 열 이름을 알기쉽게 변경
cars.columns = ['차종구분', '신청번호', '지급일자', '차종', '신청대수', '신청자명', '주소',
       '총액', '국비', '도비', '시비', '추가', '차량번호',
       '차대번호', '차량출고일', '차량등록일']

# 불필요한 열은 삭제
cars = cars.drop(['차종구분', '신청번호', '차량출고일'], axis=1)
cars

,지급일자,차종,신청대수,신청자명,주소,총액,국비,도비,시비,추가,차량번호,차대번호,차량등록일
0,2022-06-23,니로 플러스 / 일반승용,1,김명철,경기도 의정부시 흥선로82번길 27 .,900,700,0,200,0,서울31자9071,KNAA381GFPT001058,2022-06-20
1,2022-06-23,Electrified GV70 AWD 19인치 / 일반승용,1,현대캐피탈주식회사,서울특별시 영등포구 의사당대로 3 .,398.5,349,0,49.5,0,26도5369,KMTMA811PNU001795,2022-06-21
2,2022-06-23,iX3 M Sport / 일반승용,1,이정민,서울특별시 노원구 석계로 49 106동1002호,384,299,0,85,0,68저4780,WBY41DU07NS426522,2022-06-21
3,2022-06-23,EV6 롱레인지 2WD 19인치 / 일반승용,1,김종술,서울특별시 강남구 개포로 636 4층,900,700,0,200,0,서울31사2551,KNAC281AFNA067027,2022-06-17
4,2022-06-23,니로 플러스 / 일반승용,1,원태욱,서울특별시 영등포구 신풍로 77 114동 303호,900,700,0,200,0,서울31자7759,KNAA381GFPT000865,2022-06-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1343,2022-06-09,넥쏘 수소연료전지차,1,김계정,"서울특별시 노원구 섬밭로 139 110동 602호 (공릉동, 공릉풍림아파트)","3,250","2,250",0,"1,000",0,39보7457,KMHJ8816FPU026015,2022-05-23
1344,2022-06-22,넥쏘 수소연료전지차,1,김은미,서울특별시 성북구 화랑로15길 4 101동 1407호,"3,250","2,250",0,"1,000",0,07다6582,KMHJ8816FPU026197,2022-05-20
1345,2022-06-22,넥쏘 수소연료전지차,1,조현정,서울특별시 용산구 이촌로87길 21 104동 702호,"3,250","2,250",0,"1,000",0,54버3040,KMHJ8816FPU025941,2022-05-24
1346,2022-06-22,넥쏘 수소연료전지차,1,티피지이엔지 주식회사,서울특별시 양천구 목동동로 293 3304,"3,250","2,250",0,"1,000",0,45노2368,KMHJ8816FPU025291,2022-05-19
1347,2022-06-08,일렉시티 FCEV,5,공항버스(주),서울특별시 강서구 개화동로8길 17 개화동,"150,000","75,000",0,"75,000",0,서울70사8163 서울70사8164 서울70사8165 서울70사8166 서울75사1682,KMJTA18YPNC001596 KMJTA18YPNC001597 KMJTA18YPN...,2022-05-31 2022-05-31 2022-05-31 2022-05-31 20...

In [7]:
# '주소'가 '노원구'인 것들만 추출 ==> 타구 주소인데 도로명에 '노원구세군1길' 같은 것이 없는지 확인
# nowon_cars = cars[cars['주소'].str.contains('노원구')]

nowon_cars = cars[cars['주소'].str.contains('서울특별시 노원구|서울시 노원구')]
nowon_cars

,지급일자,차종,신청대수,신청자명,주소,총액,국비,도비,시비,추가,차량번호,차대번호,차량등록일
2,2022-06-23,iX3 M Sport / 일반승용,1,이정민,서울특별시 노원구 석계로 49 106동1002호,384,299,0,85,0,68저4780,WBY41DU07NS426522,2022-06-21
18,2022-06-23,EV6 롱레인지 4WD 19인치 / 일반승용,1,임채유,서울특별시 노원구 동일로 1776 2층,900,700,0,200,0,서울32자3821,KNAC381CPNA067165,2022-06-20
24,2022-06-23,니로 플러스 / 일반승용,1,백형국,서울특별시 노원구 노원로 532 909동607호,900,700,0,200,0,서울32자1679,KNAA381GFPT000874,2022-06-14
108,2022-06-16,EQA250(MY22-1) / 일반승용,1,전승수,서울특별시 노원구 광운로 86 605호,384,299,0,85,0,19수6758,W1N9N0BB6NJ035241,2022-06-03
117,2022-06-16,GV60 스탠다드 2WD 19인치 / 일반승용,1,(주)인덕쇼핑백,서울특별시 노원구 공릉로58다길 16-12 1층,400,350,0,50,0,05도5737,KMTKB81AFNU006129,2022-06-09
151,2022-06-16,Model 3(Long Range HPL) / 일반승용,1,김현화,서울특별시 노원구 초안산로2라길 26 104동 1401호,405,315,0,90,0,16주1859,5YJ3E1EB3NF229537,2022-06-07
264,2022-06-23,Model 3(Long Range HPL) / 일반승용,1,신종태,서울특별시 노원구 섬밭로 265 17동 1509호,405,315,0,90,0,05도5727,5YJ3E1EB7NF227032,2022-06-13
298,2022-06-23,Model Y Long Range 50 / 일반승용,1,권영우,서울특별시 노원구 노원로38길 76 106동 604호,405,315,0,90,0,68저4901,7SAYGDEE5NF415949,2022-06-15
350,2022-06-16,Model 3(Long Range HPL) / 일반승용,1,황정민,서울특별시 노원구 한글비석로 479 111동 101호,405,315,0,90,0,55러1867,5YJ3E1EB3NF229988,2022-06-09
451,2022-06-16,Model Y Long Range 50 / 일반승용,1,허재훈,서울특별시 노원구 섬밭로 265 6동 306호,405,315,0,90,0,16주1881,7SAYGDEE4NF414369,2022-06-02
523,2022-06-10,Model 3(Long Range HPL) / 일반승용,1,박영재,서울특별시 노원구 동일로203가길 29 1046호,405,315,0,90,0,21로7546,5YJ3E1EB1NF229147,2022-05-26
553,2022-06-08,Model 3(Long Range HPL) / 일반승용,1,김진호,서울특별시 노원구 동일로216길 92 2동 1107호,405,315,0,90,0,54무6377,5YJ3E1EB9NF229137,2022-05-23
572,2022-06-23,EV6 롱레인지 4WD 19인치 / 일반승용,1,이병칠,서울특별시 노원구 동일로 1776 .,900,700,0,200,0,서울32자6253,KNAC381CPNA067151,2022-06-15
605,2022-06-16,GV60 스탠다드 2WD 19인치 / 일반승용,1,정병희,"서울특별시 노원구 공릉로59길 25 708동605호(하계동,청솔아파트)",450,350,0,100,0,08로1388,KMTKB81AFNU006148,2022-06-10
608,2022-06-23,EV6 롱레인지 4WD 19인치 / 일반승용,1,임채일,서울특별시 노원구 동일로 1776 2층,900,700,0,200,0,서울32자5070,KNAC381CPNA067720,2022-06-13
638,2022-06-10,EV6 롱레인지 2WD 19인치 / 일반승용,1,인병일,서울특별시 노원구 덕릉로60길 222 101동 503호,900,700,0,200,0,서울31자6182,KNAC381AFNA063815,2022-05-30
641,2022-06-10,Electrified GV70 AWD 19인치 / 일반승용,1,정경두,서울특별시 노원구 화랑로 564 102동 801호,448,349,0,99,0,08러8136,KMTMA811PNU001350,2022-05-27
653,2022-06-10,EV6 스탠다드 4WD 19인치 / 일반승용,1,장소현,서울특별시 노원구 동일로208길 20 207동409호,900,700,0,200,0,48나7598,KNAC281DPNA064660,2022-05-31
665,2022-06-10,아이오닉5 2WD 롱레인지 20인치 / 일반승용,1,유은주,"서울특별시 노원구 덕릉로 613 301동 1501호 (중계동, 우성아파트)",900,700,0,200,0,19노5799,KMHKR81AFNU105172,2022-05-31
726,2022-06-16,EV6 롱레인지 4WD 19인치 / 일반승용,1,김승환,서울특별시 노원구 중계로12길 24 10동1204호,"1,200",900,0,200,100,서울32사6989,KNAC381CPNA065917,2022-06-07
731,2022-06-16,니로 플러스 / 일반승용,1,박삼현,서울특별시 노원구 동일로228길 23 1409동902호,"1,200",900,0,200,100,서울31사3036,KNAA381GFPT000605,2022-06-07
734,2022-06-10,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,박인원,서울특별시 노원구 동일로 1456 709동808호,"1,200",900,0,200,100,서울31자2100,KMHKL81AFNU103751,2022-05-30
738,2022-06-10,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김진갑,서울특별시 노원구 마들로 31 118동702호,"1,200",900,0,200,100,서울32바5851,KMHKL81AFNU103949,2022-05-27
764,2022-06-16,니로 플러스 / 일반승용,1,최준규,서울특별시 노원구 덕릉로123길 48-2 .,"1,200",900,0,200,100,서울31바5221,KNAA381GFPT000201,2022-06-03
768,2022-06-08,아이오닉5 2WD 스탠다드 19인치 / 일반승용,1,박일규,서울특별시 노원구 덕릉로 459-21 116동204동,"1,200",900,0,200,100,서울36바1767,KMHKL81BFNU103729,2022-05-25
770,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,유민식,서울특별시 노원구 동일로231길 86 201동503호,"1,200",900,0,200,100,서울31아7894,KMHKL81AFNU104104,2022-05-25
783,2022-06-10,EV6 롱레인지 2WD 19인치 / 일반승용,1,김종경,서울특별시 노원구 동일로 1776 2층,"1,200",900,0,200,100,서울31바2669,KNAC381AFNA063950,2022-05-26
796,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김공학,서울특별시 노원구 동일로208길 19 203동406호,"1,200",900,0,200,100,서울36바1537,KMHKL81AFNU103202,2022-05-23
798,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김기창,서울특별시 노원구 동일로198가길 13 404동905호,"1,200",900,0,200,100,서울32자4032,KMHKL81AFNU103629,2022-05-25
801,2022-06-10,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,주효중,서울특별시 노원구 동일로 1776 2층,"1,200",900,0,200,100,서울31바7022,KMHKL81AFNU104348,2022-05-27
804,2022-06-23,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김현식,서울특별시 노원구 중계로 230 503-109,"1,200",900,0,200,100,서울31아2667,KMHKL81AFNU106941,2022-06-20
805,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,이전귀,서울특별시 노원구 한글비석로8길 41 601동 1505호,"1,200",900,0,200,100,서울32아1632,KMHKL81AFNU103639,2022-05-23
806,2022-06-10,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,임영균,서울특별시 노원구 마들로 111 21동 1309호,"1,200",900,0,200,100,서울32사6109,KMHKL81AFNU104523,2022-05-26
813,2022-06-23,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,곽광운,서울특별시 노원구 공릉로 213 104동 2002호,"1,200",900,0,200,100,서울32자4958,KMHKL81AFNU106945,2022-06-20
834,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김동찬,서울특별시 노원구 한글비석로 396 106동 912호,"1,200",900,0,200,100,서울31아7662,KMHKL81AFNU103276,2022-05-23
861,2022-06-16,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,백한흠,서울특별시 노원구 한글비석로54길 92 1308동 1305호,"1,200",900,0,200,100,서울31사6608,KMHKL81AFNU093542,2022-06-07
937,2022-06-08,EV6 롱레인지 2WD 19인치 / 일반승용,1,김현숙,서울특별시 노원구 동일로182길 37-19 1층,900,700,0,200,0,58서5096,KNAC381AFNA062966,2022-05-25
939,2022-06-16,EV6 롱레인지 2WD 19인치 / 일반승용,1,조승권,서울특별시 노원구 덕릉로127길 25 101-409,900,700,0,200,0,05도5091,KNAC381AFNA065678,2022-06-08
972,2022-06-16,아이오닉5 2WD 롱레인지 20인치 / 일반승용,1,박영빈,서울특별시 노원구 동일로227길 25 1101동 1204호,900,700,0,200,0,43더8211,KMHKR81AFNU105964,2022-06-03
973,2022-06-10,아이오닉5 AWD 롱레인지 20인치 / 일반승용,1,설용방,서울특별시 노원구 덕릉로84길 33 501동 305호,874,680,0,194,0,58서5240,KMHKR81CPNU104740,2022-05-27
989,2022-06-08,EV6 롱레인지 4WD 19인치 / 일반승용,1,한동순,서울특별시 노원구 동일로 1776 상계동,"1,200",900,0,200,100,서울32자4205,KNAC381CPNA063375,2022-05-24
994,2022-06-08,EV6 롱레인지 2WD 19인치 / 일반승용,1,이종우,서울특별시 노원구 동일로 1776 2층,"1,200",900,0,200,100,서울32사7271,KNAC381AFNA063578,2022-05-26
999,2022-06-10,EV6 롱레인지 2WD 19인치 / 일반승용,1,김종학,서울특별시 노원구 동일로 1776 2층,"1,200",900,0,200,100,서울31자6491,KNAC381AFNA064029,2022-05-30
1054,2022-06-23,포터Ⅱ 일렉트릭 / 화물(소형),1,권담,서울특별시 노원구 중계로8길 103 115동 610호,"2,000","1,400",0,600,0,87가4028,KMFZCZ7NFNU033546,2022-06-10
1055,2022-06-09,포터Ⅱ 일렉트릭 / 화물(소형),1,이현우,서울특별시 노원구 초안산로1길 18 311동602호,"2,000","1,400",0,600,0,84루7961,KMFZCZ7NFNU033269,2022-06-03
1073,2022-06-09,봉고Ⅲ 전기차 / 화물(소형),1,임현수,서울특별시 노원구 공릉로43가길 6 402호,"2,140","1,540",0,600,0,88가1486,KNCSJZ7NFNK023153,2022-05-26
1095,2022-06-23,포터Ⅱ 일렉트릭 / 화물(소형),1,양창순,서울특별시 노원구 동일로195길 39 102동1602호,"2,000","1,400",0,600,0,92보2389,KMFZCZ7NFNU033218,2022-06-03
1116,2022-06-09,포터Ⅱ 일렉트릭 / 화물(소형),1,신동균,서울특별시 노원구 동일로187길 12-16 1층,"2,000","1,400",0,600,0,97가8022,KMFZCZ7NFNU033232,2022-06-03
1171,2022-06-09,포터Ⅱ 일렉트릭 / 화물(소형),1,유성희,서울특별시 노원구 공릉로34길 86 103동1403호,"2,000","1,400",0,600,0,87가4131,KMFZCZ7NFNU032498,2022-05-26
1183,2022-06-23,포터Ⅱ 일렉트릭 / 화물(소형),1,임재민,서울특별시 노원구 한글비석로48길 6 5동 810호,"2,000","1,400",0,600,0,81로4433,KMFZCZ7NFNU033580,2022-06-13
1187,2022-06-23,봉고Ⅲ 전기차 / 화물(소형),1,양지운,서울특별시 노원구 초안산로1길 15 104동 103호,"2,000","1,400",0,600,0,서울80배8355,KNFSTZ7NFNK023845,2022-06-09
1188,2022-06-09,포터Ⅱ 일렉트릭 / 화물(소형),1,이장열,"서울특별시 노원구 한글비석로41길 3 3층 9호(상계동, 한성빌라)","2,140","1,540",0,600,0,91노1335,KMFZCZ7NFNU033088,2022-06-02
1189,2022-06-23,포터Ⅱ 일렉트릭 / 화물(소형),1,오대균,서울특별시 노원구 동일로176길 39-12 101동 110호,"2,000","1,400",0,600,0,96모3295,KMFZCZ7NFNU033257,2022-06-03
1228,2022-06-22,넥쏘 수소연료전지차,1,류경화,서울특별시 노원구 한글비석로54길 92 1301-212(상계주공아파트),"3,250","2,250",0,"1,000",0,43더8159,KMHJ8816FPU026291,2022-05-27
1254,2022-06-28,넥쏘 수소연료전지차,1,정덕화,서울특별시 노원구 동일로214길 21 417-104,"3,250","2,250",0,"1,000",0,08로1108,KMHJ8816FPU026991,2022-06-07
1300,2022-06-22,넥쏘 수소연료전지차,1,김장호,서울특별시 노원구 동일로207길 186 110-1604,"3,250","2,250",0,"1,000",0,58서4935,KMHJ8816FPU026281,2022-05-20
1328,2022-06-22,넥쏘 수소연료전지차,1,채연석,서울특별시 노원구 마들로 127 34동103호,"3,250","2,250",0,"1,000",0,19누8735,KMHJ8816FPU026317,2022-05-26
1343,2022-06-09,넥쏘 수소연료전지차,1,김계정,"서울특별시 노원구 섬밭로 139 110동 602호 (공릉동, 공릉풍림아파트)","3,250","2,250",0,"1,000",0,39보7457,KMHJ8816FPU026015,2022-05-23

In [8]:
# 신청대수가 2대 이상인 경우 걸러내기(엑셀 행 1개에 여러대인 경우 1/N)
# ==> 아무것도 나오지 않아야 정상
nowon_cars[nowon_cars['신청대수'] != '1']

Empty DataFrame
Columns: [지급일자, 차종, 신청대수, 신청자명, 주소, 총액, 국비, 도비, 시비, 추가, 차량번호, 차대번호, 차량등록일]
Index: []

In [9]:
# 도비가 0이 아닌 비정상적인 경우를 걸러내기(서울시는 도비가 없음)
# ==> 아무것도 나오지 않아야 정상
nowon_cars[nowon_cars['도비'] != '0']

Empty DataFrame
Columns: [지급일자, 차종, 신청대수, 신청자명, 주소, 총액, 국비, 도비, 시비, 추가, 차량번호, 차대번호, 차량등록일]
Index: []

In [10]:
# 도비는 모두 0이므로 열을 지운다
nowon_cars = nowon_cars.drop(['도비'], axis=1)
nowon_cars

,지급일자,차종,신청대수,신청자명,주소,총액,국비,시비,추가,차량번호,차대번호,차량등록일
2,2022-06-23,iX3 M Sport / 일반승용,1,이정민,서울특별시 노원구 석계로 49 106동1002호,384,299,85,0,68저4780,WBY41DU07NS426522,2022-06-21
18,2022-06-23,EV6 롱레인지 4WD 19인치 / 일반승용,1,임채유,서울특별시 노원구 동일로 1776 2층,900,700,200,0,서울32자3821,KNAC381CPNA067165,2022-06-20
24,2022-06-23,니로 플러스 / 일반승용,1,백형국,서울특별시 노원구 노원로 532 909동607호,900,700,200,0,서울32자1679,KNAA381GFPT000874,2022-06-14
108,2022-06-16,EQA250(MY22-1) / 일반승용,1,전승수,서울특별시 노원구 광운로 86 605호,384,299,85,0,19수6758,W1N9N0BB6NJ035241,2022-06-03
117,2022-06-16,GV60 스탠다드 2WD 19인치 / 일반승용,1,(주)인덕쇼핑백,서울특별시 노원구 공릉로58다길 16-12 1층,400,350,50,0,05도5737,KMTKB81AFNU006129,2022-06-09
151,2022-06-16,Model 3(Long Range HPL) / 일반승용,1,김현화,서울특별시 노원구 초안산로2라길 26 104동 1401호,405,315,90,0,16주1859,5YJ3E1EB3NF229537,2022-06-07
264,2022-06-23,Model 3(Long Range HPL) / 일반승용,1,신종태,서울특별시 노원구 섬밭로 265 17동 1509호,405,315,90,0,05도5727,5YJ3E1EB7NF227032,2022-06-13
298,2022-06-23,Model Y Long Range 50 / 일반승용,1,권영우,서울특별시 노원구 노원로38길 76 106동 604호,405,315,90,0,68저4901,7SAYGDEE5NF415949,2022-06-15
350,2022-06-16,Model 3(Long Range HPL) / 일반승용,1,황정민,서울특별시 노원구 한글비석로 479 111동 101호,405,315,90,0,55러1867,5YJ3E1EB3NF229988,2022-06-09
451,2022-06-16,Model Y Long Range 50 / 일반승용,1,허재훈,서울특별시 노원구 섬밭로 265 6동 306호,405,315,90,0,16주1881,7SAYGDEE4NF414369,2022-06-02
523,2022-06-10,Model 3(Long Range HPL) / 일반승용,1,박영재,서울특별시 노원구 동일로203가길 29 1046호,405,315,90,0,21로7546,5YJ3E1EB1NF229147,2022-05-26
553,2022-06-08,Model 3(Long Range HPL) / 일반승용,1,김진호,서울특별시 노원구 동일로216길 92 2동 1107호,405,315,90,0,54무6377,5YJ3E1EB9NF229137,2022-05-23
572,2022-06-23,EV6 롱레인지 4WD 19인치 / 일반승용,1,이병칠,서울특별시 노원구 동일로 1776 .,900,700,200,0,서울32자6253,KNAC381CPNA067151,2022-06-15
605,2022-06-16,GV60 스탠다드 2WD 19인치 / 일반승용,1,정병희,"서울특별시 노원구 공릉로59길 25 708동605호(하계동,청솔아파트)",450,350,100,0,08로1388,KMTKB81AFNU006148,2022-06-10
608,2022-06-23,EV6 롱레인지 4WD 19인치 / 일반승용,1,임채일,서울특별시 노원구 동일로 1776 2층,900,700,200,0,서울32자5070,KNAC381CPNA067720,2022-06-13
638,2022-06-10,EV6 롱레인지 2WD 19인치 / 일반승용,1,인병일,서울특별시 노원구 덕릉로60길 222 101동 503호,900,700,200,0,서울31자6182,KNAC381AFNA063815,2022-05-30
641,2022-06-10,Electrified GV70 AWD 19인치 / 일반승용,1,정경두,서울특별시 노원구 화랑로 564 102동 801호,448,349,99,0,08러8136,KMTMA811PNU001350,2022-05-27
653,2022-06-10,EV6 스탠다드 4WD 19인치 / 일반승용,1,장소현,서울특별시 노원구 동일로208길 20 207동409호,900,700,200,0,48나7598,KNAC281DPNA064660,2022-05-31
665,2022-06-10,아이오닉5 2WD 롱레인지 20인치 / 일반승용,1,유은주,"서울특별시 노원구 덕릉로 613 301동 1501호 (중계동, 우성아파트)",900,700,200,0,19노5799,KMHKR81AFNU105172,2022-05-31
726,2022-06-16,EV6 롱레인지 4WD 19인치 / 일반승용,1,김승환,서울특별시 노원구 중계로12길 24 10동1204호,"1,200",900,200,100,서울32사6989,KNAC381CPNA065917,2022-06-07
731,2022-06-16,니로 플러스 / 일반승용,1,박삼현,서울특별시 노원구 동일로228길 23 1409동902호,"1,200",900,200,100,서울31사3036,KNAA381GFPT000605,2022-06-07
734,2022-06-10,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,박인원,서울특별시 노원구 동일로 1456 709동808호,"1,200",900,200,100,서울31자2100,KMHKL81AFNU103751,2022-05-30
738,2022-06-10,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김진갑,서울특별시 노원구 마들로 31 118동702호,"1,200",900,200,100,서울32바5851,KMHKL81AFNU103949,2022-05-27
764,2022-06-16,니로 플러스 / 일반승용,1,최준규,서울특별시 노원구 덕릉로123길 48-2 .,"1,200",900,200,100,서울31바5221,KNAA381GFPT000201,2022-06-03
768,2022-06-08,아이오닉5 2WD 스탠다드 19인치 / 일반승용,1,박일규,서울특별시 노원구 덕릉로 459-21 116동204동,"1,200",900,200,100,서울36바1767,KMHKL81BFNU103729,2022-05-25
770,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,유민식,서울특별시 노원구 동일로231길 86 201동503호,"1,200",900,200,100,서울31아7894,KMHKL81AFNU104104,2022-05-25
783,2022-06-10,EV6 롱레인지 2WD 19인치 / 일반승용,1,김종경,서울특별시 노원구 동일로 1776 2층,"1,200",900,200,100,서울31바2669,KNAC381AFNA063950,2022-05-26
796,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김공학,서울특별시 노원구 동일로208길 19 203동406호,"1,200",900,200,100,서울36바1537,KMHKL81AFNU103202,2022-05-23
798,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김기창,서울특별시 노원구 동일로198가길 13 404동905호,"1,200",900,200,100,서울32자4032,KMHKL81AFNU103629,2022-05-25
801,2022-06-10,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,주효중,서울특별시 노원구 동일로 1776 2층,"1,200",900,200,100,서울31바7022,KMHKL81AFNU104348,2022-05-27
804,2022-06-23,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김현식,서울특별시 노원구 중계로 230 503-109,"1,200",900,200,100,서울31아2667,KMHKL81AFNU106941,2022-06-20
805,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,이전귀,서울특별시 노원구 한글비석로8길 41 601동 1505호,"1,200",900,200,100,서울32아1632,KMHKL81AFNU103639,2022-05-23
806,2022-06-10,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,임영균,서울특별시 노원구 마들로 111 21동 1309호,"1,200",900,200,100,서울32사6109,KMHKL81AFNU104523,2022-05-26
813,2022-06-23,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,곽광운,서울특별시 노원구 공릉로 213 104동 2002호,"1,200",900,200,100,서울32자4958,KMHKL81AFNU106945,2022-06-20
834,2022-06-08,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,김동찬,서울특별시 노원구 한글비석로 396 106동 912호,"1,200",900,200,100,서울31아7662,KMHKL81AFNU103276,2022-05-23
861,2022-06-16,아이오닉5 2WD 롱레인지 19인치 빌트인 캠 미적용 / 일반승용,1,백한흠,서울특별시 노원구 한글비석로54길 92 1308동 1305호,"1,200",900,200,100,서울31사6608,KMHKL81AFNU093542,2022-06-07
937,2022-06-08,EV6 롱레인지 2WD 19인치 / 일반승용,1,김현숙,서울특별시 노원구 동일로182길 37-19 1층,900,700,200,0,58서5096,KNAC381AFNA062966,2022-05-25
939,2022-06-16,EV6 롱레인지 2WD 19인치 / 일반승용,1,조승권,서울특별시 노원구 덕릉로127길 25 101-409,900,700,200,0,05도5091,KNAC381AFNA065678,2022-06-08
972,2022-06-16,아이오닉5 2WD 롱레인지 20인치 / 일반승용,1,박영빈,서울특별시 노원구 동일로227길 25 1101동 1204호,900,700,200,0,43더8211,KMHKR81AFNU105964,2022-06-03
973,2022-06-10,아이오닉5 AWD 롱레인지 20인치 / 일반승용,1,설용방,서울특별시 노원구 덕릉로84길 33 501동 305호,874,680,194,0,58서5240,KMHKR81CPNU104740,2022-05-27
989,2022-06-08,EV6 롱레인지 4WD 19인치 / 일반승용,1,한동순,서울특별시 노원구 동일로 1776 상계동,"1,200",900,200,100,서울32자4205,KNAC381CPNA063375,2022-05-24
994,2022-06-08,EV6 롱레인지 2WD 19인치 / 일반승용,1,이종우,서울특별시 노원구 동일로 1776 2층,"1,200",900,200,100,서울32사7271,KNAC381AFNA063578,2022-05-26
999,2022-06-10,EV6 롱레인지 2WD 19인치 / 일반승용,1,김종학,서울특별시 노원구 동일로 1776 2층,"1,200",900,200,100,서울31자6491,KNAC381AFNA064029,2022-05-30
1054,2022-06-23,포터Ⅱ 일렉트릭 / 화물(소형),1,권담,서울특별시 노원구 중계로8길 103 115동 610호,"2,000","1,400",600,0,87가4028,KMFZCZ7NFNU033546,2022-06-10
1055,2022-06-09,포터Ⅱ 일렉트릭 / 화물(소형),1,이현우,서울특별시 노원구 초안산로1길 18 311동602호,"2,000","1,400",600,0,84루7961,KMFZCZ7NFNU033269,2022-06-03
1073,2022-06-09,봉고Ⅲ 전기차 / 화물(소형),1,임현수,서울특별시 노원구 공릉로43가길 6 402호,"2,140","1,540",600,0,88가1486,KNCSJZ7NFNK023153,2022-05-26
1095,2022-06-23,포터Ⅱ 일렉트릭 / 화물(소형),1,양창순,서울특별시 노원구 동일로195길 39 102동1602호,"2,000","1,400",600,0,92보2389,KMFZCZ7NFNU033218,2022-06-03
1116,2022-06-09,포터Ⅱ 일렉트릭 / 화물(소형),1,신동균,서울특별시 노원구 동일로187길 12-16 1층,"2,000","1,400",600,0,97가8022,KMFZCZ7NFNU033232,2022-06-03
1171,2022-06-09,포터Ⅱ 일렉트릭 / 화물(소형),1,유성희,서울특별시 노원구 공릉로34길 86 103동1403호,"2,000","1,400",600,0,87가4131,KMFZCZ7NFNU032498,2022-05-26
1183,2022-06-23,포터Ⅱ 일렉트릭 / 화물(소형),1,임재민,서울특별시 노원구 한글비석로48길 6 5동 810호,"2,000","1,400",600,0,81로4433,KMFZCZ7NFNU033580,2022-06-13
1187,2022-06-23,봉고Ⅲ 전기차 / 화물(소형),1,양지운,서울특별시 노원구 초안산로1길 15 104동 103호,"2,000","1,400",600,0,서울80배8355,KNFSTZ7NFNK023845,2022-06-09
1188,2022-06-09,포터Ⅱ 일렉트릭 / 화물(소형),1,이장열,"서울특별시 노원구 한글비석로41길 3 3층 9호(상계동, 한성빌라)","2,140","1,540",600,0,91노1335,KMFZCZ7NFNU033088,2022-06-02
1189,2022-06-23,포터Ⅱ 일렉트릭 / 화물(소형),1,오대균,서울특별시 노원구 동일로176길 39-12 101동 110호,"2,000","1,400",600,0,96모3295,KMFZCZ7NFNU033257,2022-06-03
1228,2022-06-22,넥쏘 수소연료전지차,1,류경화,서울특별시 노원구 한글비석로54길 92 1301-212(상계주공아파트),"3,250","2,250","1,000",0,43더8159,KMHJ8816FPU026291,2022-05-27
1254,2022-06-28,넥쏘 수소연료전지차,1,정덕화,서울특별시 노원구 동일로214길 21 417-104,"3,250","2,250","1,000",0,08로1108,KMHJ8816FPU026991,2022-06-07
1300,2022-06-22,넥쏘 수소연료전지차,1,김장호,서울특별시 노원구 동일로207길 186 110-1604,"3,250","2,250","1,000",0,58서4935,KMHJ8816FPU026281,2022-05-20
1328,2022-06-22,넥쏘 수소연료전지차,1,채연석,서울특별시 노원구 마들로 127 34동103호,"3,250","2,250","1,000",0,19누8735,KMHJ8816FPU026317,2022-05-26
1343,2022-06-09,넥쏘 수소연료전지차,1,김계정,"서울특별시 노원구 섬밭로 139 110동 602호 (공릉동, 공릉풍림아파트)","3,250","2,250","1,000",0,39보7457,KMHJ8816FPU026015,2022-05-23

In [11]:
# 이제 확인이 끝났으므로 불필요한 '차종', '신청대수', '주소' 열을 지운다.
nowon_cars = nowon_cars.drop(['차종', '신청대수', '주소'], axis=1)
nowon_cars

,지급일자,신청자명,총액,국비,시비,추가,차량번호,차대번호,차량등록일
2,2022-06-23,이정민,384,299,85,0,68저4780,WBY41DU07NS426522,2022-06-21
18,2022-06-23,임채유,900,700,200,0,서울32자3821,KNAC381CPNA067165,2022-06-20
24,2022-06-23,백형국,900,700,200,0,서울32자1679,KNAA381GFPT000874,2022-06-14
108,2022-06-16,전승수,384,299,85,0,19수6758,W1N9N0BB6NJ035241,2022-06-03
117,2022-06-16,(주)인덕쇼핑백,400,350,50,0,05도5737,KMTKB81AFNU006129,2022-06-09
151,2022-06-16,김현화,405,315,90,0,16주1859,5YJ3E1EB3NF229537,2022-06-07
264,2022-06-23,신종태,405,315,90,0,05도5727,5YJ3E1EB7NF227032,2022-06-13
298,2022-06-23,권영우,405,315,90,0,68저4901,7SAYGDEE5NF415949,2022-06-15
350,2022-06-16,황정민,405,315,90,0,55러1867,5YJ3E1EB3NF229988,2022-06-09
451,2022-06-16,허재훈,405,315,90,0,16주1881,7SAYGDEE4NF414369,2022-06-02
523,2022-06-10,박영재,405,315,90,0,21로7546,5YJ3E1EB1NF229147,2022-05-26
553,2022-06-08,김진호,405,315,90,0,54무6377,5YJ3E1EB9NF229137,2022-05-23
572,2022-06-23,이병칠,900,700,200,0,서울32자6253,KNAC381CPNA067151,2022-06-15
605,2022-06-16,정병희,450,350,100,0,08로1388,KMTKB81AFNU006148,2022-06-10
608,2022-06-23,임채일,900,700,200,0,서울32자5070,KNAC381CPNA067720,2022-06-13
638,2022-06-10,인병일,900,700,200,0,서울31자6182,KNAC381AFNA063815,2022-05-30
641,2022-06-10,정경두,448,349,99,0,08러8136,KMTMA811PNU001350,2022-05-27
653,2022-06-10,장소현,900,700,200,0,48나7598,KNAC281DPNA064660,2022-05-31
665,2022-06-10,유은주,900,700,200,0,19노5799,KMHKR81AFNU105172,2022-05-31
726,2022-06-16,김승환,"1,200",900,200,100,서울32사6989,KNAC381CPNA065917,2022-06-07
731,2022-06-16,박삼현,"1,200",900,200,100,서울31사3036,KNAA381GFPT000605,2022-06-07
734,2022-06-10,박인원,"1,200",900,200,100,서울31자2100,KMHKL81AFNU103751,2022-05-30
738,2022-06-10,김진갑,"1,200",900,200,100,서울32바5851,KMHKL81AFNU103949,2022-05-27
764,2022-06-16,최준규,"1,200",900,200,100,서울31바5221,KNAA381GFPT000201,2022-06-03
768,2022-06-08,박일규,"1,200",900,200,100,서울36바1767,KMHKL81BFNU103729,2022-05-25
770,2022-06-08,유민식,"1,200",900,200,100,서울31아7894,KMHKL81AFNU104104,2022-05-25
783,2022-06-10,김종경,"1,200",900,200,100,서울31바2669,KNAC381AFNA063950,2022-05-26
796,2022-06-08,김공학,"1,200",900,200,100,서울36바1537,KMHKL81AFNU103202,2022-05-23
798,2022-06-08,김기창,"1,200",900,200,100,서울32자4032,KMHKL81AFNU103629,2022-05-25
801,2022-06-10,주효중,"1,200",900,200,100,서울31바7022,KMHKL81AFNU104348,2022-05-27
804,2022-06-23,김현식,"1,200",900,200,100,서울31아2667,KMHKL81AFNU106941,2022-06-20
805,2022-06-08,이전귀,"1,200",900,200,100,서울32아1632,KMHKL81AFNU103639,2022-05-23
806,2022-06-10,임영균,"1,200",900,200,100,서울32사6109,KMHKL81AFNU104523,2022-05-26
813,2022-06-23,곽광운,"1,200",900,200,100,서울32자4958,KMHKL81AFNU106945,2022-06-20
834,2022-06-08,김동찬,"1,200",900,200,100,서울31아7662,KMHKL81AFNU103276,2022-05-23
861,2022-06-16,백한흠,"1,200",900,200,100,서울31사6608,KMHKL81AFNU093542,2022-06-07
937,2022-06-08,김현숙,900,700,200,0,58서5096,KNAC381AFNA062966,2022-05-25
939,2022-06-16,조승권,900,700,200,0,05도5091,KNAC381AFNA065678,2022-06-08
972,2022-06-16,박영빈,900,700,200,0,43더8211,KMHKR81AFNU105964,2022-06-03
973,2022-06-10,설용방,874,680,194,0,58서5240,KMHKR81CPNU104740,2022-05-27
989,2022-06-08,한동순,"1,200",900,200,100,서울32자4205,KNAC381CPNA063375,2022-05-24
994,2022-06-08,이종우,"1,200",900,200,100,서울32사7271,KNAC381AFNA063578,2022-05-26
999,2022-06-10,김종학,"1,200",900,200,100,서울31자6491,KNAC381AFNA064029,2022-05-30
1054,2022-06-23,권담,"2,000","1,400",600,0,87가4028,KMFZCZ7NFNU033546,2022-06-10
1055,2022-06-09,이현우,"2,000","1,400",600,0,84루7961,KMFZCZ7NFNU033269,2022-06-03
1073,2022-06-09,임현수,"2,140","1,540",600,0,88가1486,KNCSJZ7NFNK023153,2022-05-26
1095,2022-06-23,양창순,"2,000","1,400",600,0,92보2389,KMFZCZ7NFNU033218,2022-06-03
1116,2022-06-09,신동균,"2,000","1,400",600,0,97가8022,KMFZCZ7NFNU033232,2022-06-03
1171,2022-06-09,유성희,"2,000","1,400",600,0,87가4131,KMFZCZ7NFNU032498,2022-05-26
1183,2022-06-23,임재민,"2,000","1,400",600,0,81로4433,KMFZCZ7NFNU033580,2022-06-13
1187,2022-06-23,양지운,"2,000","1,400",600,0,서울80배8355,KNFSTZ7NFNK023845,2022-06-09
1188,2022-06-09,이장열,"2,140","1,540",600,0,91노1335,KMFZCZ7NFNU033088,2022-06-02
1189,2022-06-23,오대균,"2,000","1,400",600,0,96모3295,KMFZCZ7NFNU033257,2022-06-03
1228,2022-06-22,류경화,"3,250","2,250","1,000",0,43더8159,KMHJ8816FPU026291,2022-05-27
1254,2022-06-28,정덕화,"3,250","2,250","1,000",0,08로1108,KMHJ8816FPU026991,2022-06-07
1300,2022-06-22,김장호,"3,250","2,250","1,000",0,58서4935,KMHJ8816FPU026281,2022-05-20
1328,2022-06-22,채연석,"3,250","2,250","1,000",0,19누8735,KMHJ8816FPU026317,2022-05-26
1343,2022-06-09,김계정,"3,250","2,250","1,000",0,39보7457,KMHJ8816FPU026015,2022-05-23

In [12]:
# 4개 열(총액, 국비, 시비, 추가) 문자열 ==> 정수형으로 변환 + 천단위 콤마 제거
nowon_cars[['총액', '국비', '시비', '추가']] = nowon_cars[['총액', '국비', '시비', '추가']].apply(lambda x: pd.to_numeric(x.astype(str).str.replace(',',''), errors='coerce'))
nowon_cars.dtypes

지급일자     string
신청자명     string
총액        int64
국비        int64
시비        int64
추가        int64
차량번호     string
차대번호     string
차량등록일    string
dtype: object

In [13]:
nowon_cars

,지급일자,신청자명,총액,국비,시비,추가,차량번호,차대번호,차량등록일
2,2022-06-23,이정민,384,299,85,0,68저4780,WBY41DU07NS426522,2022-06-21
18,2022-06-23,임채유,900,700,200,0,서울32자3821,KNAC381CPNA067165,2022-06-20
24,2022-06-23,백형국,900,700,200,0,서울32자1679,KNAA381GFPT000874,2022-06-14
108,2022-06-16,전승수,384,299,85,0,19수6758,W1N9N0BB6NJ035241,2022-06-03
117,2022-06-16,(주)인덕쇼핑백,400,350,50,0,05도5737,KMTKB81AFNU006129,2022-06-09
151,2022-06-16,김현화,405,315,90,0,16주1859,5YJ3E1EB3NF229537,2022-06-07
264,2022-06-23,신종태,405,315,90,0,05도5727,5YJ3E1EB7NF227032,2022-06-13
298,2022-06-23,권영우,405,315,90,0,68저4901,7SAYGDEE5NF415949,2022-06-15
350,2022-06-16,황정민,405,315,90,0,55러1867,5YJ3E1EB3NF229988,2022-06-09
451,2022-06-16,허재훈,405,315,90,0,16주1881,7SAYGDEE4NF414369,2022-06-02
523,2022-06-10,박영재,405,315,90,0,21로7546,5YJ3E1EB1NF229147,2022-05-26
553,2022-06-08,김진호,405,315,90,0,54무6377,5YJ3E1EB9NF229137,2022-05-23
572,2022-06-23,이병칠,900,700,200,0,서울32자6253,KNAC381CPNA067151,2022-06-15
605,2022-06-16,정병희,450,350,100,0,08로1388,KMTKB81AFNU006148,2022-06-10
608,2022-06-23,임채일,900,700,200,0,서울32자5070,KNAC381CPNA067720,2022-06-13
638,2022-06-10,인병일,900,700,200,0,서울31자6182,KNAC381AFNA063815,2022-05-30
641,2022-06-10,정경두,448,349,99,0,08러8136,KMTMA811PNU001350,2022-05-27
653,2022-06-10,장소현,900,700,200,0,48나7598,KNAC281DPNA064660,2022-05-31
665,2022-06-10,유은주,900,700,200,0,19노5799,KMHKR81AFNU105172,2022-05-31
726,2022-06-16,김승환,1200,900,200,100,서울32사6989,KNAC381CPNA065917,2022-06-07
731,2022-06-16,박삼현,1200,900,200,100,서울31사3036,KNAA381GFPT000605,2022-06-07
734,2022-06-10,박인원,1200,900,200,100,서울31자2100,KMHKL81AFNU103751,2022-05-30
738,2022-06-10,김진갑,1200,900,200,100,서울32바5851,KMHKL81AFNU103949,2022-05-27
764,2022-06-16,최준규,1200,900,200,100,서울31바5221,KNAA381GFPT000201,2022-06-03
768,2022-06-08,박일규,1200,900,200,100,서울36바1767,KMHKL81BFNU103729,2022-05-25
770,2022-06-08,유민식,1200,900,200,100,서울31아7894,KMHKL81AFNU104104,2022-05-25
783,2022-06-10,김종경,1200,900,200,100,서울31바2669,KNAC381AFNA063950,2022-05-26
796,2022-06-08,김공학,1200,900,200,100,서울36바1537,KMHKL81AFNU103202,2022-05-23
798,2022-06-08,김기창,1200,900,200,100,서울32자4032,KMHKL81AFNU103629,2022-05-25
801,2022-06-10,주효중,1200,900,200,100,서울31바7022,KMHKL81AFNU104348,2022-05-27
804,2022-06-23,김현식,1200,900,200,100,서울31아2667,KMHKL81AFNU106941,2022-06-20
805,2022-06-08,이전귀,1200,900,200,100,서울32아1632,KMHKL81AFNU103639,2022-05-23
806,2022-06-10,임영균,1200,900,200,100,서울32사6109,KMHKL81AFNU104523,2022-05-26
813,2022-06-23,곽광운,1200,900,200,100,서울32자4958,KMHKL81AFNU106945,2022-06-20
834,2022-06-08,김동찬,1200,900,200,100,서울31아7662,KMHKL81AFNU103276,2022-05-23
861,2022-06-16,백한흠,1200,900,200,100,서울31사6608,KMHKL81AFNU093542,2022-06-07
937,2022-06-08,김현숙,900,700,200,0,58서5096,KNAC381AFNA062966,2022-05-25
939,2022-06-16,조승권,900,700,200,0,05도5091,KNAC381AFNA065678,2022-06-08
972,2022-06-16,박영빈,900,700,200,0,43더8211,KMHKR81AFNU105964,2022-06-03
973,2022-06-10,설용방,874,680,194,0,58서5240,KMHKR81CPNU104740,2022-05-27
989,2022-06-08,한동순,1200,900,200,100,서울32자4205,KNAC381CPNA063375,2022-05-24
994,2022-06-08,이종우,1200,900,200,100,서울32사7271,KNAC381AFNA063578,2022-05-26
999,2022-06-10,김종학,1200,900,200,100,서울31자6491,KNAC381AFNA064029,2022-05-30
1054,2022-06-23,권담,2000,1400,600,0,87가4028,KMFZCZ7NFNU033546,2022-06-10
1055,2022-06-09,이현우,2000,1400,600,0,84루7961,KMFZCZ7NFNU033269,2022-06-03
1073,2022-06-09,임현수,2140,1540,600,0,88가1486,KNCSJZ7NFNK023153,2022-05-26
1095,2022-06-23,양창순,2000,1400,600,0,92보2389,KMFZCZ7NFNU033218,2022-06-03
1116,2022-06-09,신동균,2000,1400,600,0,97가8022,KMFZCZ7NFNU033232,2022-06-03
1171,2022-06-09,유성희,2000,1400,600,0,87가4131,KMFZCZ7NFNU032498,2022-05-26
1183,2022-06-23,임재민,2000,1400,600,0,81로4433,KMFZCZ7NFNU033580,2022-06-13
1187,2022-06-23,양지운,2000,1400,600,0,서울80배8355,KNFSTZ7NFNK023845,2022-06-09
1188,2022-06-09,이장열,2140,1540,600,0,91노1335,KMFZCZ7NFNU033088,2022-06-02
1189,2022-06-23,오대균,2000,1400,600,0,96모3295,KMFZCZ7NFNU033257,2022-06-03
1228,2022-06-22,류경화,3250,2250,1000,0,43더8159,KMHJ8816FPU026291,2022-05-27
1254,2022-06-28,정덕화,3250,2250,1000,0,08로1108,KMHJ8816FPU026991,2022-06-07
1300,2022-06-22,김장호,3250,2250,1000,0,58서4935,KMHJ8816FPU026281,2022-05-20
1328,2022-06-22,채연석,3250,2250,1000,0,19누8735,KMHJ8816FPU026317,2022-05-26
1343,2022-06-09,김계정,3250,2250,1000,0,39보7457,KMHJ8816FPU026015,2022-05-23

In [14]:
# 총액 = 국비 + 시비 + 추가 ==> 금액이 맞는지 확인 ==> 나오는 게 없어야 정상
nowon_cars[nowon_cars['총액'] != nowon_cars['국비'] + nowon_cars['시비'] + nowon_cars['추가']]

Empty DataFrame
Columns: [지급일자, 신청자명, 총액, 국비, 시비, 추가, 차량번호, 차대번호, 차량등록일]
Index: []

In [15]:
# 특기사항이 화면에 모두 출력될 수 있도록 열의 최대출력 길이 변경
pd.set_option('display.max_colwidth', 200)

# 인덱스(행 이름) 0부터 정렬 + dataframe 이름 변경
df = nowon_cars.reset_index(drop=True)
df

,지급일자,신청자명,총액,국비,시비,추가,차량번호,차대번호,차량등록일
0,2022-06-23,이정민,384,299,85,0,68저4780,WBY41DU07NS426522,2022-06-21
1,2022-06-23,임채유,900,700,200,0,서울32자3821,KNAC381CPNA067165,2022-06-20
2,2022-06-23,백형국,900,700,200,0,서울32자1679,KNAA381GFPT000874,2022-06-14
3,2022-06-16,전승수,384,299,85,0,19수6758,W1N9N0BB6NJ035241,2022-06-03
4,2022-06-16,(주)인덕쇼핑백,400,350,50,0,05도5737,KMTKB81AFNU006129,2022-06-09
5,2022-06-16,김현화,405,315,90,0,16주1859,5YJ3E1EB3NF229537,2022-06-07
6,2022-06-23,신종태,405,315,90,0,05도5727,5YJ3E1EB7NF227032,2022-06-13
7,2022-06-23,권영우,405,315,90,0,68저4901,7SAYGDEE5NF415949,2022-06-15
8,2022-06-16,황정민,405,315,90,0,55러1867,5YJ3E1EB3NF229988,2022-06-09
9,2022-06-16,허재훈,405,315,90,0,16주1881,7SAYGDEE4NF414369,2022-06-02
10,2022-06-10,박영재,405,315,90,0,21로7546,5YJ3E1EB1NF229147,2022-05-26
11,2022-06-08,김진호,405,315,90,0,54무6377,5YJ3E1EB9NF229137,2022-05-23
12,2022-06-23,이병칠,900,700,200,0,서울32자6253,KNAC381CPNA067151,2022-06-15
13,2022-06-16,정병희,450,350,100,0,08로1388,KMTKB81AFNU006148,2022-06-10
14,2022-06-23,임채일,900,700,200,0,서울32자5070,KNAC381CPNA067720,2022-06-13
15,2022-06-10,인병일,900,700,200,0,서울31자6182,KNAC381AFNA063815,2022-05-30
16,2022-06-10,정경두,448,349,99,0,08러8136,KMTMA811PNU001350,2022-05-27
17,2022-06-10,장소현,900,700,200,0,48나7598,KNAC281DPNA064660,2022-05-31
18,2022-06-10,유은주,900,700,200,0,19노5799,KMHKR81AFNU105172,2022-05-31
19,2022-06-16,김승환,1200,900,200,100,서울32사6989,KNAC381CPNA065917,2022-06-07
20,2022-06-16,박삼현,1200,900,200,100,서울31사3036,KNAA381GFPT000605,2022-06-07
21,2022-06-10,박인원,1200,900,200,100,서울31자2100,KMHKL81AFNU103751,2022-05-30
22,2022-06-10,김진갑,1200,900,200,100,서울32바5851,KMHKL81AFNU103949,2022-05-27
23,2022-06-16,최준규,1200,900,200,100,서울31바5221,KNAA381GFPT000201,2022-06-03
24,2022-06-08,박일규,1200,900,200,100,서울36바1767,KMHKL81BFNU103729,2022-05-25
25,2022-06-08,유민식,1200,900,200,100,서울31아7894,KMHKL81AFNU104104,2022-05-25
26,2022-06-10,김종경,1200,900,200,100,서울31바2669,KNAC381AFNA063950,2022-05-26
27,2022-06-08,김공학,1200,900,200,100,서울36바1537,KMHKL81AFNU103202,2022-05-23
28,2022-06-08,김기창,1200,900,200,100,서울32자4032,KMHKL81AFNU103629,2022-05-25
29,2022-06-10,주효중,1200,900,200,100,서울31바7022,KMHKL81AFNU104348,2022-05-27
30,2022-06-23,김현식,1200,900,200,100,서울31아2667,KMHKL81AFNU106941,2022-06-20
31,2022-06-08,이전귀,1200,900,200,100,서울32아1632,KMHKL81AFNU103639,2022-05-23
32,2022-06-10,임영균,1200,900,200,100,서울32사6109,KMHKL81AFNU104523,2022-05-26
33,2022-06-23,곽광운,1200,900,200,100,서울32자4958,KMHKL81AFNU106945,2022-06-20
34,2022-06-08,김동찬,1200,900,200,100,서울31아7662,KMHKL81AFNU103276,2022-05-23
35,2022-06-16,백한흠,1200,900,200,100,서울31사6608,KMHKL81AFNU093542,2022-06-07
36,2022-06-08,김현숙,900,700,200,0,58서5096,KNAC381AFNA062966,2022-05-25
37,2022-06-16,조승권,900,700,200,0,05도5091,KNAC381AFNA065678,2022-06-08
38,2022-06-16,박영빈,900,700,200,0,43더8211,KMHKR81AFNU105964,2022-06-03
39,2022-06-10,설용방,874,680,194,0,58서5240,KMHKR81CPNU104740,2022-05-27
40,2022-06-08,한동순,1200,900,200,100,서울32자4205,KNAC381CPNA063375,2022-05-24
41,2022-06-08,이종우,1200,900,200,100,서울32사7271,KNAC381AFNA063578,2022-05-26
42,2022-06-10,김종학,1200,900,200,100,서울31자6491,KNAC381AFNA064029,2022-05-30
43,2022-06-23,권담,2000,1400,600,0,87가4028,KMFZCZ7NFNU033546,2022-06-10
44,2022-06-09,이현우,2000,1400,600,0,84루7961,KMFZCZ7NFNU033269,2022-06-03
45,2022-06-09,임현수,2140,1540,600,0,88가1486,KNCSJZ7NFNK023153,2022-05-26
46,2022-06-23,양창순,2000,1400,600,0,92보2389,KMFZCZ7NFNU033218,2022-06-03
47,2022-06-09,신동균,2000,1400,600,0,97가8022,KMFZCZ7NFNU033232,2022-06-03
48,2022-06-09,유성희,2000,1400,600,0,87가4131,KMFZCZ7NFNU032498,2022-05-26
49,2022-06-23,임재민,2000,1400,600,0,81로4433,KMFZCZ7NFNU033580,2022-06-13
50,2022-06-23,양지운,2000,1400,600,0,서울80배8355,KNFSTZ7NFNK023845,2022-06-09
51,2022-06-09,이장열,2140,1540,600,0,91노1335,KMFZCZ7NFNU033088,2022-06-02
52,2022-06-23,오대균,2000,1400,600,0,96모3295,KMFZCZ7NFNU033257,2022-06-03
53,2022-06-22,류경화,3250,2250,1000,0,43더8159,KMHJ8816FPU026291,2022-05-27
54,2022-06-28,정덕화,3250,2250,1000,0,08로1108,KMHJ8816FPU026991,2022-06-07
55,2022-06-22,김장호,3250,2250,1000,0,58서4935,KMHJ8816FPU026281,2022-05-20
56,2022-06-22,채연석,3250,2250,1000,0,19누8735,KMHJ8816FPU026317,2022-05-26
57,2022-06-09,김계정,3250,2250,1000,0,39보7457,KMHJ8816FPU026015,2022-05-23

In [16]:
# 서울시 공문번호 입력
doc_num = "서울시 기후변화대응과-24031(2022.06.17.)"

# 특기사항 입력
# 서울특별시, 전기차 구매보조금 339만원(국비 264만원, 시비 75만원, 지급일자 2022.5.24.) 서울시 기후변화대응과-24031(2022.06.17.)
df['특기사항'] = "서울특별시, 전기차 구매보조금 " + (df['총액']).astype('str') + "만원 (국비 " + (df['국비']).astype('str') + "만원, 시비 " + (df['시비'] + df['추가']).astype('str') + "만원, 지급일자 " + df['지급일자'] + ") " + doc_num
df

,지급일자,신청자명,총액,국비,시비,추가,차량번호,차대번호,차량등록일,특기사항
0,2022-06-23,이정민,384,299,85,0,68저4780,WBY41DU07NS426522,2022-06-21,"서울특별시, 전기차 구매보조금 384만원 (국비 299만원, 시비 85만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
1,2022-06-23,임채유,900,700,200,0,서울32자3821,KNAC381CPNA067165,2022-06-20,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
2,2022-06-23,백형국,900,700,200,0,서울32자1679,KNAA381GFPT000874,2022-06-14,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
3,2022-06-16,전승수,384,299,85,0,19수6758,W1N9N0BB6NJ035241,2022-06-03,"서울특별시, 전기차 구매보조금 384만원 (국비 299만원, 시비 85만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
4,2022-06-16,(주)인덕쇼핑백,400,350,50,0,05도5737,KMTKB81AFNU006129,2022-06-09,"서울특별시, 전기차 구매보조금 400만원 (국비 350만원, 시비 50만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
5,2022-06-16,김현화,405,315,90,0,16주1859,5YJ3E1EB3NF229537,2022-06-07,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
6,2022-06-23,신종태,405,315,90,0,05도5727,5YJ3E1EB7NF227032,2022-06-13,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
7,2022-06-23,권영우,405,315,90,0,68저4901,7SAYGDEE5NF415949,2022-06-15,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
8,2022-06-16,황정민,405,315,90,0,55러1867,5YJ3E1EB3NF229988,2022-06-09,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
9,2022-06-16,허재훈,405,315,90,0,16주1881,7SAYGDEE4NF414369,2022-06-02,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
10,2022-06-10,박영재,405,315,90,0,21로7546,5YJ3E1EB1NF229147,2022-05-26,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
11,2022-06-08,김진호,405,315,90,0,54무6377,5YJ3E1EB9NF229137,2022-05-23,"서울특별시, 전기차 구매보조금 405만원 (국비 315만원, 시비 90만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
12,2022-06-23,이병칠,900,700,200,0,서울32자6253,KNAC381CPNA067151,2022-06-15,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
13,2022-06-16,정병희,450,350,100,0,08로1388,KMTKB81AFNU006148,2022-06-10,"서울특별시, 전기차 구매보조금 450만원 (국비 350만원, 시비 100만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
14,2022-06-23,임채일,900,700,200,0,서울32자5070,KNAC381CPNA067720,2022-06-13,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
15,2022-06-10,인병일,900,700,200,0,서울31자6182,KNAC381AFNA063815,2022-05-30,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
16,2022-06-10,정경두,448,349,99,0,08러8136,KMTMA811PNU001350,2022-05-27,"서울특별시, 전기차 구매보조금 448만원 (국비 349만원, 시비 99만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
17,2022-06-10,장소현,900,700,200,0,48나7598,KNAC281DPNA064660,2022-05-31,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
18,2022-06-10,유은주,900,700,200,0,19노5799,KMHKR81AFNU105172,2022-05-31,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
19,2022-06-16,김승환,1200,900,200,100,서울32사6989,KNAC381CPNA065917,2022-06-07,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
20,2022-06-16,박삼현,1200,900,200,100,서울31사3036,KNAA381GFPT000605,2022-06-07,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
21,2022-06-10,박인원,1200,900,200,100,서울31자2100,KMHKL81AFNU103751,2022-05-30,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
22,2022-06-10,김진갑,1200,900,200,100,서울32바5851,KMHKL81AFNU103949,2022-05-27,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
23,2022-06-16,최준규,1200,900,200,100,서울31바5221,KNAA381GFPT000201,2022-06-03,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
24,2022-06-08,박일규,1200,900,200,100,서울36바1767,KMHKL81BFNU103729,2022-05-25,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
25,2022-06-08,유민식,1200,900,200,100,서울31아7894,KMHKL81AFNU104104,2022-05-25,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
26,2022-06-10,김종경,1200,900,200,100,서울31바2669,KNAC381AFNA063950,2022-05-26,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
27,2022-06-08,김공학,1200,900,200,100,서울36바1537,KMHKL81AFNU103202,2022-05-23,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
28,2022-06-08,김기창,1200,900,200,100,서울32자4032,KMHKL81AFNU103629,2022-05-25,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
29,2022-06-10,주효중,1200,900,200,100,서울31바7022,KMHKL81AFNU104348,2022-05-27,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
30,2022-06-23,김현식,1200,900,200,100,서울31아2667,KMHKL81AFNU106941,2022-06-20,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
31,2022-06-08,이전귀,1200,900,200,100,서울32아1632,KMHKL81AFNU103639,2022-05-23,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
32,2022-06-10,임영균,1200,900,200,100,서울32사6109,KMHKL81AFNU104523,2022-05-26,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
33,2022-06-23,곽광운,1200,900,200,100,서울32자4958,KMHKL81AFNU106945,2022-06-20,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
34,2022-06-08,김동찬,1200,900,200,100,서울31아7662,KMHKL81AFNU103276,2022-05-23,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
35,2022-06-16,백한흠,1200,900,200,100,서울31사6608,KMHKL81AFNU093542,2022-06-07,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
36,2022-06-08,김현숙,900,700,200,0,58서5096,KNAC381AFNA062966,2022-05-25,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
37,2022-06-16,조승권,900,700,200,0,05도5091,KNAC381AFNA065678,2022-06-08,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
38,2022-06-16,박영빈,900,700,200,0,43더8211,KMHKR81AFNU105964,2022-06-03,"서울특별시, 전기차 구매보조금 900만원 (국비 700만원, 시비 200만원, 지급일자 2022-06-16) 서울시 기후변화대응과-24031(2022.06.17.)"
39,2022-06-10,설용방,874,680,194,0,58서5240,KMHKR81CPNU104740,2022-05-27,"서울특별시, 전기차 구매보조금 874만원 (국비 680만원, 시비 194만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
40,2022-06-08,한동순,1200,900,200,100,서울32자4205,KNAC381CPNA063375,2022-05-24,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
41,2022-06-08,이종우,1200,900,200,100,서울32사7271,KNAC381AFNA063578,2022-05-26,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-08) 서울시 기후변화대응과-24031(2022.06.17.)"
42,2022-06-10,김종학,1200,900,200,100,서울31자6491,KNAC381AFNA064029,2022-05-30,"서울특별시, 전기차 구매보조금 1200만원 (국비 900만원, 시비 300만원, 지급일자 2022-06-10) 서울시 기후변화대응과-24031(2022.06.17.)"
43,2022-06-23,권담,2000,1400,600,0,87가4028,KMFZCZ7NFNU033546,2022-06-10,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
44,2022-06-09,이현우,2000,1400,600,0,84루7961,KMFZCZ7NFNU033269,2022-06-03,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022-06-09) 서울시 기후변화대응과-24031(2022.06.17.)"
45,2022-06-09,임현수,2140,1540,600,0,88가1486,KNCSJZ7NFNK023153,2022-05-26,"서울특별시, 전기차 구매보조금 2140만원 (국비 1540만원, 시비 600만원, 지급일자 2022-06-09) 서울시 기후변화대응과-24031(2022.06.17.)"
46,2022-06-23,양창순,2000,1400,600,0,92보2389,KMFZCZ7NFNU033218,2022-06-03,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
47,2022-06-09,신동균,2000,1400,600,0,97가8022,KMFZCZ7NFNU033232,2022-06-03,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022-06-09) 서울시 기후변화대응과-24031(2022.06.17.)"
48,2022-06-09,유성희,2000,1400,600,0,87가4131,KMFZCZ7NFNU032498,2022-05-26,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022-06-09) 서울시 기후변화대응과-24031(2022.06.17.)"
49,2022-06-23,임재민,2000,1400,600,0,81로4433,KMFZCZ7NFNU033580,2022-06-13,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
50,2022-06-23,양지운,2000,1400,600,0,서울80배8355,KNFSTZ7NFNK023845,2022-06-09,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
51,2022-06-09,이장열,2140,1540,600,0,91노1335,KMFZCZ7NFNU033088,2022-06-02,"서울특별시, 전기차 구매보조금 2140만원 (국비 1540만원, 시비 600만원, 지급일자 2022-06-09) 서울시 기후변화대응과-24031(2022.06.17.)"
52,2022-06-23,오대균,2000,1400,600,0,96모3295,KMFZCZ7NFNU033257,2022-06-03,"서울특별시, 전기차 구매보조금 2000만원 (국비 1400만원, 시비 600만원, 지급일자 2022-06-23) 서울시 기후변화대응과-24031(2022.06.17.)"
53,2022-06-22,류경화,3250,2250,1000,0,43더8159,KMHJ8816FPU026291,2022-05-27,"서울특별시, 전기차 구매보조금 3250만원 (국비 2250만원, 시비 1000만원, 지급일자 2022-06-22) 서울시 기후변화대응과-24031(2022.06.17.)"
54,2022-06-28,정덕화,3250,2250,1000,0,08로1108,KMHJ8816FPU026991,2022-06-07,"서울특별시, 전기차 구매보조금 3250만원 (국비 2250만원, 시비 1000만원, 지급일자 2022-06-28) 서울시 기후변화대응과-24031(2022.06.17.)"
55,2022-06-22,김장호,3250,2250,1000,0,58서4935,KMHJ8816FPU026281,2022-05-20,"서울특별시, 전기차 구매보조금 3250만원 (국비 2250만원, 시비 1000만원, 지급일자 2022-06-22) 서울시 기후변화대응과-24031(2022.06.17.)"
56,2022-06-22,채연석,3250,2250,1000,0,19누8735,KMHJ8816FPU026317,2022-05-26,"서울특별시, 전기차 구매보조금 3250만원 (국비 2250만원, 시비 1000만원, 지급일자 2022-06-22) 서울시 기후변화대응과-24031(2022.06.17.)"
57,2022-06-09,김계정,3250,2250,1000,0,39보7457,KMHJ8816FPU026015,2022-05-23,"서울특별시, 전기차 구매보조금 3250만원 (국비 2250만원, 시비 1000만원, 지급일자 2022-06-09) 서울시 기후변화대응과-24031(2022.06.17.)"

In [17]:
# pip install XlsxWriter

writer = pd.ExcelWriter("2022_07_보조금.xlsx") 
df.to_excel(writer, sheet_name='보조금', index=False)

for column in df:
    column_length = max(df[column].astype(str).map(len).max(), len(column))
    col_idx = df.columns.get_loc(column)
    writer.sheets['보조금'].set_column(col_idx, col_idx, column_length*1.3)    # 한글 때문에 X1.3으로 열너비 늘렸다.

writer.save()

### 전처리로 만들어진 xlsx 파일 ==> 후처리에서 특기사항 입력